### ISSUE TITLE
City panel closes but production panel remains open

### ISSUE THREAD

**Issue by olegbl** [chaorace/cqui#10]
The city panel and city overview panel both close while the production panel remains open. This occurs when starting a new building production in a district (one that hasn't been started before). The panels close and an animation plays on the district where the building is being built.

**Comment by chaorace** [comment]
Same issue can be triggered by purchasing buildings with gold

**Comment by chaorace** [comment]
Fixed in #12 for now. Will revisit implementation in the future

**Comment by chaorace** [comment]
Finally slain this issue once and for all with the cityview rewrite
