### ISSUE TITLE
No option to build an army or corps in latest nightly

### ISSUE THREAD

**Issue by angelodgreat** [chaorace/cqui#100]
There is no option to build an army or corps in the latest nightly
![123](https://cloud.githubusercontent.com/assets/20021423/20296101/dfccfd42-ab43-11e6-8353-c032a62b429a.png)

**Comment by chaorace** [comment]
Yay 100th tracked issue! I completely forgot about the corps button, could you provide the save so I have a game with corps to test with?

**Comment by m4potofu** [comment]
here is one

https://drive.google.com/file/d/0B5ks0hYTUQxQbUw3MDhIanRMTDQ/view?usp=sharing

but it's very quick to set up if you start at info era with online speed.

**Comment by chaorace** [comment]
By the way, you can revert to the last nightly before I started working on merging the production tabs for now if you like. [Here's the link](https://github.com/chaorace/cqui/archive/74613b494c67a8f8c922cbc6b36518b1a5d9f6ce.zip)

**Comment by angelodgreat** [comment]
thanks
