### ISSUE TITLE
finished production sometimes shows previous prod instead of the one that just finished

### ISSUE THREAD

**Issue by m4potofu** [chaorace/cqui#101]
ex :
builder finished : http://i.imgur.com/NKmxiL1.jpg
finished prod shows spearman built previously : http://i.imgur.com/KKOWsry.jpg

Latest files, no other mods.

**Comment by chaorace** [comment]
iirc this is a bug in the base game as well

**Comment by RatchetJ** [comment]
I have a fix for this mostly ready to go. The only issue is if you save a game when a city needs to choose production. Do you know a good way to save a variable inside the game save, then retrieve it once the game is loaded?

**Comment by chaorace** [comment]
@RatchetJ GameConfiguration.SetValue(keyname, value) sets and GameConfiguration.GetValue(keyname) gets. I'm pretty sure you can even purge values using GameConfiguration.SetValue(keyname, nil)

**Comment by RatchetJ** [comment]
@chaorace What about saving a table? Is there something different I have to do in that case? I'm looking into how to do a deep copy in lua.

**Comment by chaorace** [comment]
@RatchetJ I've no idea. actually. It might just work out of the box if we're lucky
