### ISSUE TITLE
[Latest Nightly] Can't Repair Pillaged Districts

### ISSUE THREAD

**Issue by Qwynn** [chaorace/cqui#109]
I've seem to run into an issue of being unable to repair pillaged districts in the most recent build. The city window shows that the district is damaged and the turns needed to repair it, but I can't actually select the option.

![desktop 2016-11-17 10-14-50 am-354](https://cloud.githubusercontent.com/assets/23527032/20394990/67ba1c32-acaf-11e6-8286-b5d1aa141585.png)

**Comment by Qwynn** [comment]
Apparently you cannot repair districts you don't, uh, have the tech for. Never mind, I was silly. Simply never came across that before.

**Comment by chaorace** [comment]
lol
