### ISSUE TITLE
Implement the Civ V hotkeys where appropriate

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#11]
Things like: Fortify until Heal, Cycle units, etc. I'd also like to implement wasd scrolling, but that has the potential to conflict with some of the V bindings. Maybe have two modes configurable from mod options?

**Comment by kemikalz** [comment]
Hi there. Here is how to add cycle to the next unit (unfortified) & next city:

1. Open Sid Meier's Civilization VI\Base\Assets\UI\WorldInput.lua

2. Fine the function DefaultKeyDownHandler (line 916 in the original file)

3. Add the following after the last if/then statement but above "return false;":

-- START: select next unit
if (uiKey == Keys.**YOUR_KEY_HERE**) then
    UI.SelectNextReadyUnit();
end
-- END: select next unit

-- START: select next city
if (uiKey == Keys.**YOUR_KEY_HERE**) then
    local kCity:table = UI.GetHeadSelectedCity();
    UI.SelectNextCity(kCity);
    UI.PlaySound("UI_Click_Sweetener_Metal_Button_Small");
end
-- END: select next city

4. Change "YOUR_KEY_HERE" to whatever you want to use.

I've been using the unit cycle for a while now, and it works great. I have "W" set to next unit and "D" to end turn in the game options. AFIAK there's nothing out in the wild on how to cycle backwards through units/cities. I've not used the city one, but i am sure it works the same way.

Thanks for all the hard work everyone here is putting into this :)

**Comment by jacks0nX** [comment]
SelectPrevCity() is the function for the previous city.

**Comment by chaorace** [comment]
Yeah, this one's easy to do and high demand, I know of at least a handful of people waiting specifically for this feature. If this isn't implemented by the time I get home today I'll assign it to myself and get cracking

**Comment by chaorace** [comment]
All done! I went a little overboard with reimplementing EVERY bind, then I even added an enhanced mode with some really slick nav controls. Check it out!

**Comment by chaorace** [comment]
Implemented in 70c5fbbcffa08d36576220abc01813cc7c295d92
