### ISSUE TITLE
Fall 2016 patch compatibility

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#111]
This issue should serve as the central place for fixing issues caused by the new patch as well as bringing new patch features under the fold.

Just reviewing the patch notes, it looks like then following will need to be implemented:

- [x] Any broken UI elements that need fixing?
Nope!
- [x] Add city rename UI back
- [x] City governor buttons in citypanel are broken
- [x] Remove Next Plot mod, since that's now a game feature (we'll want to port any features from the mod over that aren't in the base game implementation though!)
I've consolidated the new cultural plot growth overlay and the existing plotinfo UI into something quite nice! Another issue bites the dust
- [ ] BTS custom localizations are broken (potentially an issue from before the fall patch, needs more investigation)
- [ ] Anything else?

**Comment by chaorace** [comment]
Okay, comparing strictly the UI files, there are 129 differences. Here's [a link](http://pastebin.com/3m8BMLUi) to the report

The following changes affect the CQUI mod files as they are now:

```
CQUI:
CivilopediaSupport.lua                        4 Differences
CityPanel.lua                                 12 Differences
CityPanel.xml                                 2 Differences
CityPanelOverview.lua                         8 Differences
CityPanelOverview.xml                         6 Differences
ProductionPanel.lua                           12 Differences
TechTree.lua                                  5 Differences
PlotToolTip.lua                               11 Differences
ActionPanel.lua                               19 Differences
WorldInput.lua                                7 Differences
WorldViewIconsManager.lua                     3 Differences
TopPanel.xml                                  1 Differences
PlotInfo.lua                                  4 Differences
PlotInfo.xml                                  3 Differences
CityBannerManager.lua                         15 Differences
CityBannerManager.xml                         5 Differences
GovernmentScreen.lua                          6 Differences
GovernmentScreen.xml                          3 Differences
CivicsTree.lua                                5 Differences
TechCivicCompletedPopup.lua                   2 Differences
UnitPanel.lua                                 3 Differences

BTS:
TradeOverview.lua                             4 Differences
TradeOriginChooser.lua                        1 Differences

URS:
ReportScreen.lua                              22 Differences
ReportScreen.xml                              8 Differences
```

The good news is that nothing seems immediately broken, so yay!

**Comment by chaorace** [comment]
I've created a new branch for committing fixes dedicated to transitioning towards 1.0.0.38. Feel free to help out with knocking these changes out!

**Comment by ProustIdee** [comment]
Regarding BTS localization, apparently you have to restart after changing the language? Referenced by Astog here:

https://forums.civfanatics.com/threads/better-trade-screen.602636/page-5#post-14570570

**Comment by ProustIdee** [comment]
Science advisor recommends everything in the science and tech trees:

![2016-11-19 13_26_26-sid meier s civilization vi dx12](https://cloud.githubusercontent.com/assets/15386719/20457546/ec7349e6-ae5b-11e6-8262-112ee25b0d54.png)

![2016-11-19 13_27_00-sid meier s civilization vi dx12](https://cloud.githubusercontent.com/assets/15386719/20457547/ec737d44-ae5b-11e6-892c-230b1279e8bc.png)

**Comment by chaorace** [comment]
All's fix now, hooray!

**Comment by Fangh** [comment]
Do we need to wait for a new release to use cqui with the fall patch ? Thank you for your work !

**Comment by chaorace** [comment]
@Fangh You just need to download the latest nightly. v0.7 is coring soon though, just need to finish up integrating the production queue and improve the settings menu
