### ISSUE TITLE
unable to use ressource governers 

### ISSUE THREAD

**Issue by layzsmurf** [chaorace/cqui#113]
Today I downloaded the latest branch (not sure how versioning works). I unzipped the file and put it in the DLC folder and renamed it to CQUI.

Starting a new game in the city screen I want to select the resource governors on the top - e.g. food. The tile lights up for a short time and then is unchecked again.

Is there a close button for the CQUI setup? I found none and took me a while to figure out how to close the window.

**Comment by chaorace** [comment]
All fall 2016 patch related issues should be reported under issue #111
