### ISSUE TITLE
City Details

### ISSUE THREAD

**Issue by Spedwards** [chaorace/cqui#114]
So I thought I'd try out this mod, but immediately disabled it as soon as the City Details opened up when I opened up Production. That's a non-starter for me.

There's also no documentation as to _where_ the settings are located, so I don't even know if I can disable this. There are other things I want to change as well, like the XP bar.

**Comment by chaorace** [comment]
I'm sorry you feel that way, we all have our personal tastes. To be fair, the city details opening on city selection is the very first item in the readme file, so I'm unsure how this could have been unexpected. There is no option for disabling his, as the rest of the mod is built around the assumption that there is a single unified cityview, as opposed to modular panels.

Anyways, this issue doesn't actually seem to document anything or directly request anything, which means I'm going to be closing it. In the future, please consider sharing instead on the Civfanatics forum post or the Gitter IRC. Have a nice day!
