### ISSUE TITLE
Can't focus city production anymore

### ISSUE THREAD

**Issue by RickyMai** [chaorace/cqui#123]
I installed version 0.6 and have the updated version of Civ. 
Now I can't turn on focus the city for production/food/culture/science.
The buttons for it in the city menu don't work.

When I load a savegame without CQUI the issue isn't there.
CQUI is the only mod I use.

It's really great! Thank you for it.

**Comment by jacks0nX** [comment]
Fixed in the nightly, so the next "official" release will have this change. You can simply download the current version from here again and be fine.

**Comment by RickyMai** [comment]
That's great, thank you!
