### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by jacks0nX** [chaorace/cqui#125]
In various places translations are missing and use english instead, although often an appropriate localization is already available.

1. Find places where translations are missing
2. Fix translations
- [x] Civic notification (use LOC_CIVIC_COMPLETE or LOC_GOVT_COMPLETED_THIS_TURN)
- [x] Technology notification (use LOC_TECH_BOOST_COMPLETE)
- [ ] Tech boost notification (Tech .. one turn away.., currently no appropriate one)
- [ ] Civic boost notification (Civic .. one turn away.., currently no appropriate one)
- [x] "x/x Districts" in city panel
- [x] Tooltip for "Religious citizens" in city panel (use LOC_UI_RELIGION_NUM_FOLLOWERS_TT)
- [x] Tooltip for amenities "from population"

Custom localizations can probably be added later on.

**Comment by jacks0nX** [comment]
@chaorace could you add "add appropriate translations where possible" to the style guidelines?

**Comment by chaorace** [comment]
Part of the problem is that custom localizations are broken right now. They always break after reloading a save

**Comment by jacks0nX** [comment]
Yep, unfortunately. Set it to future revisit for now. Made some changes where it was possible though.

**Comment by chaorace** [comment]
Woops. this isn't quite 100% addressed yet, reopening

**Comment by chaorace** [comment]
CQUI has had all front-facing hardcoded strings replaced with LOCs
