### ISSUE TITLE
Remove tile masking of border expansion UI

### ISSUE THREAD

**Issue by zxcvforz** [chaorace/cqui#126]
The new border expansion UI tries to show progress to the next expansion using a solid purple fill. As can be seen below, this severely obstructs reading the tile underneath.

![289070_20161121034210_1c](https://cloud.githubusercontent.com/assets/6653593/20465721/3e23c22c-af9f-11e6-8a33-d38a9474e8e0.jpg)

With CQUI providing "in X turns" message, I'd like to suggest that the purple fill be removed completely. The border is a nice touch that makes the border expansion stand out, but the purple fill often forces me to exit the city view just to make sure what's underneath.

**Comment by chaorace** [comment]
Try clicking the button

**Comment by zxcvforz** [comment]
Ah, I see. I never realized it was clickable. Now that's a really pleasant surprise! Thanks!
