### ISSUE TITLE
Trade error captions

### ISSUE THREAD

**Issue by GrantSP** [chaorace/cqui#131]
I'm using the files from the latest repo, not that from the latest release, and I noticed this error.

![trade error](https://cloud.githubusercontent.com/assets/3291695/20508748/fae604ba-b0b7-11e6-9824-d88d77c77416.png)

**Comment by chaorace** [comment]
This is an issue with BTS mod and has already been reported to the respective mod author. This isn't directly a CQUI issue so I'm closing this for now
