### ISSUE TITLE
Compatibility with JFD's Mod.

### ISSUE THREAD

**Issue by angelodgreat** [chaorace/cqui#132]
Any chance on being compatible with JFD's Rule of faith? i found out that it causes conflict and civics wont open.

**Comment by angelodgreat** [comment]
already fixed it by commenting civictree.lua in .modinfo. thanks for your work :D

**Comment by chaorace** [comment]
@angelodgreat Nope, not gonna go particularly out of the way to make CQUI compatible with Rule of Faith. It's a great mod, but our two packages inevitably touch the same UI elements
