### ISSUE TITLE
Hover information for cities

### ISSUE THREAD

**Issue by jacks0nX** [chaorace/cqui#136]
A feature I really liked in the EUI in Civ 5 was the possibility to hover over a city's banner, thus see at a glance what tiles are currently worked by citizens and which tile the city will expand to. Additionally the cities tiles could show their yield on hover.

**Comment by zxcvforz** [comment]
On latest build, the hover information will always turn off yields display when un-hovering from the city banner. This conflicts with the global yield display option.

I would suggest that the hover function needs to be aware of the current state of yield icon display and do its work accordingly.

Should I open a new issue or does this belong within this issue? I'm sorry I'm not familiar with software development practices.
