### ISSUE TITLE
Production Queue does not advance on item completion

### ISSUE THREAD

**Issue by s-leaf83** [chaorace/cqui#137]
When I complete a Building or a Districts, the city produce Queue does not work.

**Comment by thejase** [comment]
Second that.  The chosen new production only gets added to the list.  The previously finished item isn't removed, and has to be right-clicked to continue.

**Comment by chaorace** [comment]
I've been getting multiple reports of this, thanks for adding it to the tracker. In the future. please use a more descriptive issue title, thanks!

**Comment by zyxpsilon** [comment]
Related... please refer to this CF/Post for details; https://forums.civfanatics.com/threads/cqui-a-qui-spinoff-v0-6-out.602771/page-12#post-14578353

... along with a few more issues that i really don't want to add to the Issues/Flow overhere since you'd be aware of them anyway! :)

**Comment by zeyangl** [comment]
I present a fix in #141 . Played it for awhile and it appears to work fine.

**Comment by chaorace** [comment]
@zeyangl Thanks. In the future, you can submit simple fixes like these direct from the github website by forking the repo, making your change to the file in the fork using the web editor, and then hitting the submit PR button

**Comment by chaorace** [comment]
Resolved in #141 thanks to @zeyangl

**Comment by zeyangl** [comment]
@chaorace I just don't feel comfortable editing on the fly, and not have the env setup on my pc to submit a PR either. Will definitely do if the change is more involved.
