### ISSUE TITLE
Next/Prev City button in city view doesn't hide the border expansion tile mask of the city you just left

### ISSUE THREAD

**Issue by zxcvforz** [chaorace/cqui#138]
Steps to reproduce:

1. Have more than 1 city in the game. Let's name them A and B.
2. Enter city A. City A will show its border expansion tile in purple.
3. Click on the arrow for next city to go to city B.
4. Exit city view via right-click.
5. Pan the map back to city A.
6. City A's border expansion tile mask remains visible in world view.

The title of this issue is named this way because for each city we visit via the Next/Prev arrow, the city that we have just left will have its border expansion tile mask visible. So by visiting multiple cities before we exit the city view, we can end up with multiple cities showing the mask as shown below:

![289070_20161123221411_1c](https://cloud.githubusercontent.com/assets/6653593/20565227/9c5f76a0-b1cb-11e6-8922-5f2d15716b00.jpg)

In the image above, I exited the city view while I was in Alesund, which is why Alesund's border expansion mask was hidden properly.

I have been able to reproduce this on two different saves playing different civilizations, so it shouldn't be save dependent. But here's the save for the game shown in the above image:

[BorderExpansionMaskingBug.zip](https://github.com/chaorace/cqui/files/609064/BorderExpansionMaskingBug.zip)

**Comment by jacks0nX** [comment]
Ah, noticed that myself, so that's the reason for it.

**Comment by chaorace** [comment]
Woops, typo in the text for another commit closed this issue!
