### ISSUE TITLE
[Production Queue] first unit disappears in production menu fix.

### ISSUE THREAD

**Issue by zeyangl** [chaorace/cqui#140]
When the production queue is empty, first queued unit will disappear from the unit list. A simple fix will resolve this ( as of the current master branch):

in ProductionPanel.lua:2175
--if row.Hash ~= currentProductionHash and buildQueue:CanProduce( row.Hash, true ) then
if buildQueue:CanProduce( row.Hash, true ) then

Do not check row.Hash ~= currentProductionHash will resolve this problem.

**Comment by s-leaf83** [comment]
你干嘛不直接上传代码呢？

**Comment by zeyangl** [comment]
@s-leaf83 Don't assume ppl always have the env setup to upload code, and learn not to spam comments in multiple issues please.
