### ISSUE TITLE
[Production Queue] queued unit does not disappear when completed fix

### ISSUE THREAD

**Issue by zeyangl** [chaorace/cqui#141]
As mentioned in some other issue, queued unit does not get removed when it's produced. Here is a simple fix. 

Note that in ProductionPanel.lua line 3786 and 3792, OnCityProductionCompleted function is registered twice. Search for this function, you will find two functions of the same name, remove the apparently incorrect one(has a variable named badcowboy???), and remove the extra callback registration.

You can do the same for OnCityProductionChanged.

**Comment by s-leaf83** [comment]
你干嘛不直接上传代码呢？

**Comment by chaorace** [comment]
Thanks for the fix, worked great!
