### ISSUE TITLE
List of suggestions

### ISSUE THREAD

**Issue by 0SirLoin** [chaorace/cqui#147]
Hey, 
first of all thanks for that great package. I don't know if you usually use the issues here at github to also propose suggestions. So if it isn't feel free to delete or close this issue right away!
Me and my friends came along some ideas (especially with the late game chores):
- http://www.nexusmods.com/civilisationvi/mods/39/? seems like a cool, obvious and not so hard thing to implement
- also i love the new overiew of great person points, but couldn't you also calculate and show how many turns every player needs before getting the great person?
- making the spy assigned turns longer or even configurable
- reassign button for trade routes

**Comment by chaorace** [comment]
It's perfectly acceptable to submit suggestions via the issue tracker, however, each submitted issue should be self contained and specific. For example: "Add a total row to the diplomacy view" would be an acceptable issue. I'll be closing this issue and opening three specific issues concerning the first three points. I'm unsure of what you mean by reassign button, however, so I encourage you to submit your own issue regarding that with its own dedicated description

**Comment by 0SirLoin** [comment]
Hi! Thanks for the answer and clarification.
The trade route one got lost in translation I think. But before I go into detail I figured that already has been done in the Better Trade Route 3.0 version. 
Thanks again and keep up the awesome work!
