### ISSUE TITLE
Wake fortified unit when enemy is near (Fortified Alert)

### ISSUE THREAD

**Issue by kemikalz** [chaorace/cqui#151]
**Enhancement**

Hey guys, just came across this mod on the Civ Fanatics site. It is called Fortified Alert. It wakes any units that are fortified when an enemy approaches. It will also play a sound when this happens. There's also a button called Guard to press to use the function on your units. Kind of a handy thing to have, and i thought maybe you guys might like to incorporate it into CQUI. Just thought i would bring it to your attention in case maybe you haven't seen it yet. Should be quite simple to add i believe.  Thanks for all the hard work and progress ;)

[https://forums.civfanatics.com/resources/updated-fortified-alert.25590/](url)

**Comment by Sesostrismage** [comment]
Isn't this implemented in the base game now with the Winter patch?

**Comment by chaorace** [comment]
Yes it is!
