### ISSUE TITLE
Show second-highest envoy number in City-states Overview panel

### ISSUE THREAD

**Issue by zxcvforz** [chaorace/cqui#152]
This is the suggestion mock-up:

![289070_20161130104527_1c](https://cloud.githubusercontent.com/assets/6653593/20738364/7df62368-b6ed-11e6-89ad-9f66b08440f5.jpg)

_Problem with the Unmodded UI_:

We have to always click into each to check if another civ is closing in on us for city-states for which we are the Suzerain, and we also can't tell if there are others competing for the same city-state.

_Suggestion_:

1. Show the second-highest number of envoys for each city-state on the Overview panel, as shown in the mock-up above.
2. Set the alignment anchor of the second-highest number of envoys to the bottom-right of its label, and position it against the bottom of the space. This is so that when a user uses UI scaling or manually edits font sizes, the two numbers won't overlap and will stay visually appealing.
3. Color in our own number if we are the second-highest number, as shown by the number for Geneva in the mock-up image.

_Aimed Effects of Suggestion_:

1. Tell at a glance whether any of our owned city-state are at risk from competitors.
2. Tell at a glance how fierce the competition is; e.g. Yerevan in the mock-up image is under heavy competition with Japan leading at 9 and another civ right behind Japan. Nobody is even remotely interested in Lisbon. No-one is really competing for Geneva but America has established a strong presence. Nanmadol is under active competition but it's possible to win.
3. Saves lot of clicks when deciding where to send our next Envoy.

**Comment by chaorace** [comment]
Awesome little breakdown! This is definitely something I wanna do after pushing out v0.7, thanks for submiting 👍

**Comment by Frozen-In-Ice** [comment]
This is a great enhancement idea! My only suggestion that is different than the mock-up is aligning the suzerain text with the larger envoy number. In the suggestion it kind of makes it look like the Suzerain has the lower number.
