### ISSUE TITLE
City view gold yield display gets clipped with sufficiently high yield numbers

### ISSUE THREAD

**Issue by velit** [chaorace/cqui#155]
![civilizationvi_2016-11-30_18-25-45](https://cloud.githubusercontent.com/assets/1269108/20761108/994382f4-b72a-11e6-9b68-7bbbf1a2b33c.jpg)

**Comment by chaorace** [comment]
Is that an issue in the vanilla UI as well?

**Comment by velit** [comment]
I haven't actually played a full game through without your mod so I don't know.

**Comment by ZachHaber** [comment]
I can confirm that it is an issue with the vanilla UI as well. I don't have a game where it is quite as bad, though. Just the decimal of the gold running off.

**Comment by chaorace** [comment]
I think the best solution is probably going to be stretching out that top bar on the citypanel a bit

**Comment by Frozen-In-Ice** [comment]
Is this the kind of thing you were looking for chaorace?
![screenshot 2016-12-31 01 00 23](https://cloud.githubusercontent.com/assets/19610489/21576197/d7bb3ab8-cef4-11e6-89cf-cb60089f66f8.png)

This is how it looks when you have a lower yield city.
![screenshot 2016-12-31 01 01 05](https://cloud.githubusercontent.com/assets/19610489/21576202/f9139fde-cef4-11e6-960f-c95d6e26c701.png)
