### ISSUE TITLE
Spawn notifications at 50% and 100% tech/civic progress

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#16]
This should make playing without the tech/civic popups more enjoyable and improve overall qol

**Comment by White-Oak** [comment]
Please, let there be an option for this

**Comment by RatchetJ** [comment]
@chaorace 
Interested in contributing to this project. I could work on trying to figure this out if no one is doing it already.

**Comment by chaorace** [comment]
@RatchetJ Be my guest! Also, here's a little intro:
 https://github.com/chaorace/cqui/wiki/How-to-contribute-to-CQUI
Hopefully that'll cover the basics. Just ask if you need anything at all!

**Comment by RatchetJ** [comment]
Sounds good.

**Comment by RatchetJ** [comment]
@chaorace Any ideas on how to create a notification once it's determined it should be triggered? It doesn't seem like anything in NotificationPanel.lua does the actual creation.

**Comment by chaorace** [comment]
@RatchetJ  Check out the MakeDebugNotification function

**Comment by RatchetJ** [comment]
Ahh, yep, that might work. thanks.

**Comment by RatchetJ** [comment]
Got it working using the status messages, which are a lot easier than the notifications. I know that's not what we want long term, but it's something. It spawns a new message each turn that the player is at or over 50%, and also once it's completed. More work could be done to reduce it to a certain range around 50%, or just one time once it goes over 50%. What do you think?

**Comment by benjaminjackman** [comment]
Maybe it alerts the player once and then after that not anymore. Also it might be nice to alert the player before they would cross the 50% threshold so that they can switch and then after the boost still have 1 turn left so that no science or culture is wasted.

**Comment by RatchetJ** [comment]
Right now it displays once after progress exceeds 50%, then not again until that tech/civic completes. To switch it to doing the alert 1 turn before 50% is an easy switch (I would just have to multiply something by 2), so whichever one people want. Other than that decision I think I'm ready to initiate a pull request.

**Comment by chaorace** [comment]
@RatchetJ Excellent! I believe throwing the notification 1 turn before 50% is best because it guarantees 0 wasted science points

**Comment by RatchetJ** [comment]
Done. Also just created the pull request.

**Comment by chaorace** [comment]
Resolved in PR #66
