### ISSUE TITLE
Multi-citizen assignment box doesn't resize with citizen icons

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#162]
See below:

![](http://i.imgur.com/7roiLRo.png)

**Comment by Frozen-In-Ice** [comment]
By messing with values in PlotInfo.xml I was able to get it to look like this:
![screenshot 2016-12-30 22 33 34](https://cloud.githubusercontent.com/assets/19610489/21575616/6b059ddc-cee0-11e6-94a9-68d071398a70.png)

I am not very experienced though, so I have no idea if changing those values could have broken anything. I changed some of the icon, numbers, and lines offsets as well as alignments. Here's a link to the changed [PlotInfo.xml](https://www.dropbox.com/s/2u3fca03n7uleg0/PlotInfo.xml?dl=0)
