### ISSUE TITLE
Feature Request:  Integrate "More Lenses" mod

### ISSUE THREAD

**Issue by vttale** [chaorace/cqui#164]
This is fantastic:  https://forums.civfanatics.com/threads/more-lenses.606150/

Unfortunately, it conflicts with CQUI because both edit MinimapPanel.   Could this be sorted out?

**Comment by quill18** [comment]
Yes, please!  👍

**Comment by ProustIdee** [comment]
Looks like someone already made a compatible version (see the "compatibility" section): https://forums.civfanatics.com/threads/more-lenses.606150/

Someone just needs to submit a pull request with those changes.

**Comment by astog** [comment]
Already did it.

**Comment by chaorace** [comment]
Looking into your PR now, thanks for contributing! Also, hi @quill18 !
