### ISSUE TITLE
Modifier keys for adding to production queue

### ISSUE THREAD

**Issue by emperorfool** [chaorace/cqui#167]
Civ4 used modifier keys to change how you add items to the queue.

* Normal click replaces the first item.
* SHIFT adds an item at the end. No need.
* CONTROL Inserts an item at the front.
* ALT adds a unit to the end that gets repeated forever.

The only one I feel is missing is insertion at the front of the queue. SHIFT and ALT are easier to hit than CONTROL so maybe go with one of those.

**Comment by chaorace** [comment]
These are good ideas and I'll see about getting them added!

**Comment by chaorace** [comment]
The first change has been rendered less useful with the inclusion of the option to disable the production queue (eventually I plan to allow this to be toggled on a per-city basis as well, which would completely circumvent the need to change the keymap). Infinitely repeating items were something we decided wasn't necessary with the inclusion of the queue in the first place. 

Seeing as these are the only two additions your suggested keybinds would bring, I'm going to close this issue now
