### ISSUE TITLE
Add option to repeat last production to cityview

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#17]
This would have to be a per-city option, so probably not built into the mod options menu. I'm thinking a checkbox in the production menu instead. Unsure of the plausibility of this one since it's so different from the regular toggleables

**Comment by jacks0nX** [comment]
People could probably do this with the upcoming production queue. Don't really like a checkbox, just to repeat projects. Or simply make projects repeat themselves every time they finish, that would be quite similar functionality to Civ 5.

**Comment by RealAntithesis** [comment]
I would like a repeat option (check box or whatever) to repeat the last item in the queue (obviously, at the moment, there is only one item since there is no queue), which will continue for however long the item is available for.

**Comment by chaorace** [comment]
This has become less important with the progress made in terms of the production queue (#34). So I'm removing it from the beta milestone and removing the help wanted label

**Comment by jacks0nX** [comment]
Is this even needed anymore?

**Comment by chaorace** [comment]
@jacks0nX Not particularly. I think I'll go ahead and close this in light of #34
