### ISSUE TITLE
Trade route turns to completion confusion

### ISSUE THREAD

**Issue by vttale** [chaorace/cqui#171]
Mouseover tooltips for "If started, route will complete in" -- thank you so much for improving on the default game here! -- are off.  I can't quite figure out how the number was derived, though.  

For example, I've got one route here which is 38 tiles, and it correctly observes "trips to destination: 1".  If then says it would complete in 168 turns.  OH WAIT I just figured out where the confusion is, and how it could be addressed.  It stems from the clock icon simultaneously being used to mean both relative time and absolute time.

See, I'm on turn 92.  A route that completes in 76 turns would end on turn 168.  I recommend for clarity a tooltip that doesn't use the icons and instead reads like:

Trade Route distance: 38 hexes
Trips to destination: 1
If started, route will complete in 76 turns on turn 168

That would be totally unambiguous.

**Comment by vttale** [comment]
Also, could you put in the minimum trade duration somewhere, since the game doesn't indicate it anywhere else that I can tell except for the 20 turns on standard speed mentioned in the 'pedia.  The game I'm in is using Online speed and so it was thanks to your mod that I was able to find out that minimum duration is a lot less, but not exactly what it is.  Apparently it is either 10 or 12 turns, because this same city is showing me a route to a city at distance 4 that would take two cycles, and another at distance 6 that would take just 1 cycle.

**Comment by astog** [comment]
Yes, the clock in *My Routes* tab is the relative turns, and in the rest of the tabs is the absolute turns. I could not find another icon that was still a clock.

As for the formula behind the amount of turns, I wrote that in a guide [here](https://forums.civfanatics.com/resources/trade-routes-guide.25529/#q8). It explains the formula behind it and why the base game has an irrelevant info.

**Comment by vttale** [comment]
Wow thanks for the awesome guide!

**Comment by chaorace** [comment]
@vttale Can I consider this issue resolved for the time being?

**Comment by vttale** [comment]
Well, yes and no.  There isn't an actual bug here, but there is an issue of clarity.  It'll still be confusing as is, so I think reworking the information presentation would be a big help.

**Comment by astog** [comment]
I have posted the issue into my [repo](https://github.com/astog/BTS) since it would be more relevant there.

**Comment by chaorace** [comment]
Alright, closing the issue here then
