### ISSUE TITLE
Escape to close CQUI options panel

### ISSUE THREAD

**Issue by vttale** [chaorace/cqui#173]
I keep trying to close CQUI options with Escape, which is doing nothing.  Then I look for an X and it's not there.  Finally I click the minimap button again.  Sure, I could train myself to get it right every time, but it'd be cool if the other two common methods of exiting a panel were available.

**Comment by chaorace** [comment]
Yeah, it's just something I've been dragging my feet on, definitely a thing that should have been there from the start
