### ISSUE TITLE
Resource tile icons are broken in latest patch

### ISSUE THREAD

**Issue by daviddgrohl** [chaorace/cqui#180]
When I downloaded and used this mod yesterday it worked fine. Today all my resource icons... well, have a look:
You will notice in the top left corner, the stone icons are fine until I moved a unit up and got vision of them.
![image](https://cloud.githubusercontent.com/assets/24689749/21376955/037e8dec-c6ff-11e6-9fdb-c6b7d100cd02.png)
![image](https://cloud.githubusercontent.com/assets/24689749/21376958/07ee8602-c6ff-11e6-97a0-afe5ecb520f4.png)

Everything returns to normal once I remove the mod. Any ideas on how to fix this one?

**Comment by Harkinian** [comment]
The game had an update today. It will take a while for the developer to go through all the files looking for changes. Until then all you can do is be patient.

**Comment by Tim324** [comment]
This happened to me as well. I think it is connected with the patch. Was working fine the day before.

**Comment by the-m4a** [comment]
CQUI\UI\WorldViewIconsManager.lua 
Change this line (line 93 in most recent version) to:
local textureOffsetX, textureOffsetY, textureSheet = IconManager:FindIconAtlas(iconName, 64);

The difference is the addition of the second parameter to FindIconAtlas

**Comment by Tim324** [comment]
That fixed it. Brilliant!
