### ISSUE TITLE
Patch 1.0.0.56 Compatibility (Winter Patch 2016)

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#182]
So far nothing seems as horribly broken as the Fall Patch, but it's still too early to properly tell! Gotta do some investigating...

-  [x] Issue #180 (Fixed in PR #181)

**Comment by chaorace** [comment]
Okay, comparing the files to the fall patch reveals the following relevant differences:

```
CQUI:
ActionPanel.lua
CityBannerManager.lua
CityPanel.lua
CityPanelOverview.lua
CitySupport.lua
CivicsTree.lua
GovernmentScreen.lua
GreatPeoplePopup.lua
GreatPeoplePopup.xml
MapPinPopup.lua
PlotToolTip.lua
TechTree.lua
TopPanel.lua
UnitPanel.lua
WorldInput.lua
WorldViewIconsManager.lua
BTS:
TradeOverview.lua
ML:
MinimapPanel.lua
URS:
ReportScreen.lua
ReportScreen.xml
UnitPromotionPopup.lua
```

I'm going to start with working on the affect core CQUI files and hopefully the respective mod authors (pinging @astog) for the three affected mods release updates that address their own files. If that doesn't seem to be the case after some time, I'll push out my own custom fixes for the affected mods.

**Comment by chaorace** [comment]
I've opened a new branch for accepting compatibility changes for the winter patch [here](/chaorace/cqui/tree/winter2016compat). So far everything in the CQUI list up to and including the GreatPeoplePopup.lua file have been completed

**Comment by astog** [comment]
@chaorace Is there an easy way to see what they have changed in the files?

**Comment by ProustIdee** [comment]
Here are the files from the fall patch (I have my Steam files backed up):

[Civ 6 UI Fall Patch.zip](https://github.com/chaorace/cqui/files/667197/Civ.6.UI.Fall.Patch.zip)

**Comment by astog** [comment]
@ProustIdee Thank you so much!

**Comment by emperorfool** [comment]
@ProustIdee Thanks! Do you have the original files backed up too?

**Comment by chaorace** [comment]
@astog  @emperorfool 

Alright, I've created [a repo](https://github.com/chaorace/Civ6-UIFiles) for tracking the changes to the Civ VI UI files. I figure it's not a problem redistributing these specific files since we're already redistributing them whenever we release a mod anyways (and also since it's JUST the UI files, not a complete redistribution).

Anyways, click [here](https://github.com/chaorace/Civ6-UIFiles/commit/15b3cb7af67136e266976e2ae4a3d083d4ec17d5) to see the changes the winter patch introduced
