### ISSUE TITLE
Enhancement: Show unit path when selected

### ISSUE THREAD

**Issue by Sesostrismage** [chaorace/cqui#183]
I often send my units on long trips, and I tend to forget where I'm sending them to. I'd really love to see the planned path when I select a unit with existing orders, basically seeing the same as when I select a destination to begin with.

**Comment by chaorace** [comment]
I've been considering something like this using the trade path overlay and maybe a map pin that pops up at the destination. IIRC I shelved the idea for later when I discovered how complex the unit flag system was

**Comment by emperorfool** [comment]
I do so miss the Civ5 Show Move mod. Then I read "trade path overlay" and started drooling.

* Select unit with a move order (apply to queue)
* Draw planned route to destination
* Allow planting assumed enemy ZoC tiles to alter route
* Allow manually redrawing route using control points

The route to destination alone would be awesome!

**Comment by astog** [comment]
> Allow planting assumed enemy ZoC tiles to alter route

@emperorfool Wondering, what do you mean by this?

**Comment by vttale** [comment]
Heck if it could just add a simple "which tile is this unit going to" highlight as an easy first step, that'd be a huge help.  The path can then be the next evolution.

**Comment by emperorfool** [comment]
@vttale For sure, never let perfection be the enemy of good enough. :)

@astog My ideas are for allowing you to alter a unit's path a la Civ4 with chained destinations but more intuitively. Way beyond this would let you placing markers where you think stationary enemies are located (encampments) so the path would automatically adjust to avoid them. It's very pie in the sky.

Here's a natural progression of complexity:

1. Show a marker at the destination.
2. Draw the path to the destination.
3. Color-code the path segments to denote where the unit will be at the end of each turn.
4. Fix the pathing so the unit actually *follows* that path!
