### ISSUE TITLE
Resources map icons bugged

### ISSUE THREAD

**Issue by olkhen** [chaorace/cqui#184]
Hello!

I am not sure if this is due to winter update or not, since I installed mod after the update. But all of the resource map icons are bugged. (see  picture). The only other mod i have is the restart button, but i dont think there are any conflicts. Removing quick UI fixes icons
![unnamed](https://cloud.githubusercontent.com/assets/24701663/21398728/764f2972-c776-11e6-8919-45eb76c6c813.jpg)

**Comment by astog** [comment]
This is addressed #182

**Comment by olkhen** [comment]
I apologize. I didnt think of looking in the closed section
