### ISSUE TITLE
Cycling to next city keeps the info panel from the last city open

### ISSUE THREAD

**Issue by maforget** [chaorace/cqui#19]
When you switch cities with the next city buttons in the City Panel the camera pans to the city and closes the production panel, but the info panel from the previous city stays open and can't be closed without selecting the new city and closing it with the right click. 

I was expecting that the city view would stay open and only switch to the new city. But currently it does not, forcing to click on the new city. But having to select the city just to close the windows seems like a bug, the info window should at least close.

Seems related to issue #10

**Comment by chaorace** [comment]
I can't actually get up and test right now, but could you make sure you're using the latest release?

**Comment by maforget** [comment]
Tested it with commit 147a7131f72374c17c07896d06a75d392971a02c and your relase 0.51 (which are the same, but just to make sure)

**Comment by chaorace** [comment]
I actually just got home and I'm testing it now. I'll work on fixing this now, thanks for the report and cooperation, hopefully I can knock this bug out by the end of the night!

**Comment by chaorace** [comment]
Fixed with commit 9f3433e. Another bug bites the dust
