### ISSUE TITLE
Resource icons scaling issues

### ISSUE THREAD

**Issue by likadev** [chaorace/cqui#192]
Hello, I'm having an issue with resource icons best described by an image:

![](https://i.imgur.com/t3p03ud.jpg)

Here's a screenshot of my graphics settings:
![](https://i.imgur.com/AVxxFoT.jpg?1)

I'm on Windows 10. It happens whether I use the DX12 or normal game start method.

Any ideas?

Thanks.

**Comment by chaorace** [comment]
This issue has been resolved in the latest nightly
