### ISSUE TITLE
Add Option to disable More Lenses

### ISSUE THREAD

**Issue by angelodgreat** [chaorace/cqui#193]
Add Option to disable More Lenses because my game experiences delay when i click my builder. and please have option to disable show resources when hovering city view

**Comment by astog** [comment]
On top of MinimapPanel.lua you should find the following setting:

```lua
local AUTO_APPLY_BUILDER_LENS:boolean = true;
```

If you turn that to **false**, it should disable the builder lens from auto-applying. @chaorace can possibly hook onto this variable (and others) to disable the lenses from auto applying.

**Comment by chaorace** [comment]
Yep, I'll add this to issue #134
