### ISSUE TITLE
OSX/Linux version broken

### ISSUE THREAD

**Issue by tomlon** [chaorace/cqui#195]
I'm a big fan of your mod but unfortunately after installing the latest nightly I am unable to access the city (production) screen.

I tried to restart Steam/Civ 6 app and create a new game several times with different game settings but the bug repeats every single time.
Also the city name is not displayed in the right-down city panel menu. Please, see the screenshot.

I have no other mods or DLCs installed and I'm playing on Mac with the fall patch (the winter patch not released yet for Mac). 

![civ6 quickui bug](https://cloud.githubusercontent.com/assets/24780313/21485049/84f26e2e-cb51-11e6-85d2-72739bdea0b0.jpg)

**Comment by chaorace** [comment]
I'm afraid you'll have to revert back to the ad0598a7da21b4720dbf40927b08ad5000cc6d27 nightly until the Mac version catches up. You can download that nightly [here](https://github.com/chaorace/cqui/archive/ad0598a7da21b4720dbf40927b08ad5000cc6d27.zip)

**Comment by tomlon** [comment]
I've reverted to the previous nightly as advised and the problems are gone. Thank you!

**Comment by chaorace** [comment]
Mac version is updated now, closing issue. Will open again in 10ish days when the next seasonal patch drops and the OSX version is left behind again lol

**Comment by chaorace** [comment]
Welp, we all knew it would happen again eventually... I'm now reopening this issue since the OSX (and now Linux) versions are lagging behind the PC version again

**Comment by chaorace** [comment]
Okay, since it seems OSX/Linux can access the workshop, even if they're not on the latest patch, I'm going to upload the last working CQUI nightly that supported OSX/Mac over there. Problem (kinda) solved

**Comment by chaorace** [comment]
For those curious, the last CQUI nightly that was built for the Winter Patch (the version OSX/Linux is currently on) is available for download [here](https://github.com/chaorace/cqui/archive/9aac8bdb446f1f1c4ff532cb7b2ebf71bb5ea634.zip)

**Comment by chaorace** [comment]
There is now a dedicated OSX/Linux branch (as of PR #337, thanks to @lettergram) for enjoying an up-to-date CQUI experience, even while still playing on the Winter Patch. Keep in mind that, even though it's called the OSX/Linux branch, ANY Winter patch Civ VI install will accept this version of CQUI. I am now considering this issue closed once again.

You can download the latest OSX/Linux nightly [here](https://github.com/chaorace/cqui/archive/osx-linux.zip)
