### ISSUE TITLE
About Gitter

### ISSUE THREAD

**Issue by rx65m** [chaorace/cqui#200]
Hello Chris. I've just noticed there is almost 1 month you are no replying at Gitter. Are you still active there? By the way, Happy New Year.

**Comment by rx65m** [comment]
Happily I already find your Mod at civfanatics. Now it's working awesomely !

**Comment by chaorace** [comment]
Hmmm, I had email notifications turned on, but it seems like they stopped working. Thanks for the heads up!

**Comment by rx65m** [comment]
Thanks to you for always been extremely kind and polite.
