### ISSUE TITLE
Add score information to player icons

### ISSUE THREAD

**Issue by bestekov** [chaorace/cqui#206]
This is a feature request to improve the UI to always display score information (like was possible in Civ 5). I can think of a few ways to implement this:

1. New UI element overlaying the screen
2. Add score value below player portraits

Stretch goal: Add toggle between different score values (score, domination, culture, science, religious)
Stretch goal: Reorder the portraits in score order

**Comment by bestekov** [comment]
Here's a proposed mockup:
![scoremod mockup](https://cloud.githubusercontent.com/assets/4909619/21616282/defbdd34-d1ae-11e6-8802-cb03cf3e9031.png)

**Comment by bestekov** [comment]
From looking at the files, it appears you'd need to take values that are described in the **Assets\UI\PartialScreens\WorldRankings.xml** screen and add them to the **Assets\UI\DiplomacyRibbon.xml**

**Comment by bestekov** [comment]
@chaorace , you can mark this in-progress assigned to me. I have the player score part working. Going to see about science and military score soon. I'm working in my own fork and will do a PR when I have it working.

**Comment by chaorace** [comment]
Excellent, thanks for contributing!
