### ISSUE TITLE
Hills and/or forrests lenses?

### ISSUE THREAD

**Issue by mp0011** [chaorace/cqui#213]
It's hard to tell if hex is plain or hill. Also, forests and rainforests are sometimes hard to spot (eg. with plantation or other improvement). So...

Archer lenses:
GREEN: empty plains/oceans/lakes etc,
ORANGE: plains with forrest / hill
RED: Hills with forrest (and also mountains)

**Comment by chaorace** [comment]
Hey @astog, I think this one may be best handled as part of ML

**Comment by astog** [comment]
@chaorace I posted an issue in my repo. @chaorace you can close the issue here, if you want.
