### ISSUE TITLE
Remove Diplomacy screen delay

### ISSUE THREAD

**Issue by cpinter** [chaorace/cqui#214]
Can you please add a feature that decreases (or fully removes) the delay before showing the controls on the diplomacy screen?

For example when you meet a new civ, you need to wait for the leader to finish their intros unless you hit escape, and even if you do, there is a delay (screen fades) before showing the choices to say. It would be much more convenient if the controls appeared immediately and by making the choice the leader would stop saying the current sentence and skip to the next thing.

I hope I was clear! Thanks a lot!
(If you think it's easy and can give me a place to start I could try to do a pull request)

**Comment by chaorace** [comment]
It's something I've been meaning to look into. iirc it already behaves this way if you lower the leader scene setting to static, so chances are that you can just transplant that logic, assuming the logic isn't too screwy. Best guess seems to DiplomacyActionView.lua/xml. I'm willing to bet you can just gut the animation tags from the xml if you're willing to do it rather dirty

**Comment by cpinter** [comment]
Thanks, I'll check!

**Comment by Frozen-In-Ice** [comment]
I managed to speed it up by changing the BlackFadeAnim and FadeTimerAnim to "speed=2" and ConversationSelection_Alpha and ConversationSelection_Slide to "pause=0.5". The pause used to be 2, so no wonder it took ages
