### ISSUE TITLE
Can't build ddistricts

### ISSUE THREAD

**Issue by allnamestakengithubbug** [chaorace/cqui#226]
Using the Jan 6 build, I seem to have lost the ability to construct all districts, maybe also all wonders (Colosseum at least). Things were fine earlier in the game, but now in mid-game (~t120+) I only seem to be able to construct units and buildings in existing districts. This is even when the advisor is turned on, and says "you should build an X district. Clicking on the district name zooms the map in, but does not let you select a location

**Comment by mrh-is** [comment]
I'm still seeing this bug on the most recent commit (https://github.com/chaorace/cqui/commit/5aecd9638f507c030fef023f95aa563f8a66f455).

I click on the district in the sidebar, and the camera zooms out slightly, but there are no overlays showing me where I could place a district and clicking on a hex doesn't do anything.

**Comment by chaorace** [comment]
Could you provide an affected savefile for me to test?

**Comment by mrh-is** [comment]
@chaorace: Yep, [here it is](https://www.dropbox.com/s/q6d4waub3hsjgbq/Japan%20Mods.Civ6Save?dl=0).

**Comment by allnamestakengithubbug** [comment]
Hi Chris,


Sorry for taking so long to get back to you.


I think this save is representative. I'm new to Civ 6, so even though the interface problem started much earlier, I decided to keep playing even though I could not build new districts, wonders, or other improvements requiring tile conversion like airstrips.


When you first posted that you had reverted to an earlier version of ProductionPanel.lua, I tried replacing my version with the reverted version. It did not solve the problem but this save uses the reverted version, so I have also included both copies of that file.


You mod is a *huge* improvement over the vanilla Civ6 interface, so I hope you can get this problem sorted out.


I hope this helps. If you need more info, please email me at mwyg@yahoo.com


Thanks again,


Mike

________________________________

**Comment by mrh-is** [comment]
@chaorace Were you able to reproduce?

**Comment by chaorace** [comment]
@mrh-is Oh wow sorry this fell through the cracks. I'll test that save today

**Comment by mrh-is** [comment]
Hey @chaorace, finally getting back to Civ today! Anything I can do to help? 🙂

**Comment by mrh-is** [comment]
It looks like my bug was caused by one of the other mods I had enabled. (Sorry to say that I didn't test particularly thoroughly, I just know that I disabled a few and the issue was not present in a new game.)
