### ISSUE TITLE
Switching between productions does not update the production list

### ISSUE THREAD

**Issue by jacks0nX** [chaorace/cqui#23]
Probably better worded: when building a unit/building and leaving the city view the currently built item is removed from the list of possible productions upon reentering the city view. This makes it impossible to switch production to another item and switch back to the previous one, because it's just not there.
Irrelevant in vanilla because the panel is closed on click.

**Comment by chaorace** [comment]
Are you on the latest commit? I've made [a recording of the menu working as expected](https://gfycat.com/WhisperedSimplisticJerboa) with the latest changes

**Comment by jacks0nX** [comment]
Oh, I guess not, it's working as intended.
