### ISSUE TITLE
Clean up terrain tooltip

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#232]
Currently the terrain tooltip looks pretty ugly, let's spruce it up a bit! Something like the current citypanel religion tooltip would be a good goal. We should also see about conditionally removing the more redundant info wherever possible here

Current tooltip:
![](https://i.imgur.com/QDaWZrh.png)

[More info](https://www.reddit.com/r/civ/comments/5mqlkl/long_feedback_on_civ6_from_a_longtime_series_fan/)

**Comment by emperorfool** [comment]
I also have no clue how the placement of food _after_ production—reverse from all previous civ games and even the frickin' map—made it to release.

**Comment by Frozen-In-Ice** [comment]
As for conditionally removing redundant info, removing the "(Buenos Aires)" part for city states seems obvious, and should Movement Cost be removed when there's route movement?

**Comment by Frozen-In-Ice** [comment]
@chaorace Here's what I got so far:
![screenshot 2017-01-10 15 23 18](https://cloud.githubusercontent.com/assets/19610489/21823434/fc71b36c-d748-11e6-895b-7cc273ca7331.png)
![screenshot 2017-01-10 15 23 34](https://cloud.githubusercontent.com/assets/19610489/21823436/fd83616a-d748-11e6-9710-20bfb8471026.png)
Made changes as per my above post. Also added resource icon and color coded resource names

**Comment by chaorace** [comment]
Excellent Changes! Some input:

* As per @emperorfool 's request it would be nice to have food listed above production.
* Let's further organize the tooltip with another separator
  * First section strictly terrain, with "Owner" on the first line, Tiletype/Terraintype/River combined on the second line, Resource with a (improved) next to it, if improved, on third line
  * Second section for modifiers, which is basically everything from the current first segment that didn't go in the last section
  * Third section is the same as the second section is now

**Comment by Frozen-In-Ice** [comment]
Thanks for the input, and I like the idea of the reorganized sections.
I also indented the great works, and changed their bullet point as currently hovering over a district with great works lists all the great works the same as buildings.

Forgot to take a screenshot of what it was before, but if you test it yourself you'll see that it looks awful. But now:
![screenshot 2017-01-10 15 47 57](https://cloud.githubusercontent.com/assets/19610489/21824304/cbef3490-d74c-11e6-8f68-4d3020872775.png)

**Comment by vttale** [comment]
Everybody's pissed at you.  Yep. Civ VI AI checks out.

**Comment by Frozen-In-Ice** [comment]
So I reorganized the yields so that food should appear first, production second, other stuff (gold, culture, science, faith) after that:
![screenshot 2017-01-11 09 48 09](https://cloud.githubusercontent.com/assets/19610489/21853137/e0304a38-d7e3-11e6-9b35-ab8f8602a603.png)
I'm not sure how to tell if a resource has the right improvement on it, so I'll just submit what I have.
