### ISSUE TITLE
Production button ignores clicks after game save

### ISSUE THREAD

**Issue by lftur0vich** [chaorace/cqui#245]
For the third saved game in a row I've had the city Production buttons become unresponsive upon reopening the game. Downloaded the nightly to ensure I had latest CQUI version for today. Played France for a bit and saved the game. When I reopened the game later (via resume or load game) the same thing happens, no way to access a cities production queue.

Am running the following mods in the game:
- Alternate CIv Colors
- CQUI (BTS, CQUI, ML, PQ, UI, URS)
- Detailed Worlds
- Diplomatic Total
- Less Gossips

Game file enclosed for verification.
[CATHERINE DE MEDICI 82 850 BC.Civ6Save.zip](https://github.com/chaorace/cqui/files/705568/CATHERINE.DE.MEDICI.82.850.BC.Civ6Save.zip)

Playing Civ VI v1.0.0.56 (144924) on Mac OS via Steam with all released DLCs

**Comment by agaier** [comment]
Same problem, could be a coincidence but also playing as France.

**Comment by lftur0vich** [comment]
Had same issue playing England and Japan before this game. Three games, well developed I can't finish.

**Comment by chaorace** [comment]
Thanks for the heads up, I'll start looking into this

**Comment by chaorace** [comment]
I noticed your save uses Divine Yuri's City Panel mod. This mod is not only outdated and may cause conflicts with the latest civ release, but it's also incompatible with CQUI. A special version of Yuri's Panel already exists in CQUI, so there's no reason to want to load it separately anyways. I am almost certain this is the root cause of your production panel issue. I've force loaded your save without Yuri's Panel enabled and I've been unable to reproduce your described issue. Included below is a version of your save with all mod dependencies stripped except CQUI, please test it and tell me if the issue persists

https://drive.google.com/uc?id=0BzRHuYM0ypGoR2hHZU9LaDJXOTg

**Comment by lftur0vich** [comment]
Not at computer where I can view game file but I'll double check on Yuri mod soonest and let you know. Was pretty sure I'd removed it but if not then it was user error and not your fine mod.

**Comment by lftur0vich** [comment]
You're correct, the new file works just fine now, thx for that.  In my swapping around of mods I thought I'd gotten rid of all the old ones before starting new games. It's obvious that I didn't so thx for pointing that out. I'll be more careful going forward. Sorry to bother you with an obvious error on my part.

Final question though, what application did you use to edit the save file to remove mod reference? I tried removing the reference using BBEdit ( a Mac text editor that sometimes works on hex files) but it corrupted the save file so badly Civ VI couldn't get to the main menu page anymore.

**Comment by chaorace** [comment]
No need to apologize, it's an honest mistake! I created the stripped save by force loading the save and then saving the game normally. The method I use for force loading saves is using the firetuner tool from the civ5 sdk to re-enable the load button (that's actually it. Just turning the button back on is all you need to do). The save you create after force loading will only have the mods currently installed listed as dependencies

You can do this yourself in firetuner by setting the context to loadmenu (there's three of these contexts listed for some reason, the second one is the real one), then entering the following command:
'controls.actionbutton:setdisabled(false)'

Keep in mind using firetuner and saving will mark the file with a flag that blocks achievements. You'll also have to check the "enable tuner" option in the game options for firetuner to work at all
