### ISSUE TITLE
Feature Request: Housing is shown as a difference in the city banner

### ISSUE THREAD

**Issue by astog** [chaorace/cqui#255]
Can the housing number be a difference between the **used** and the **available** housing. Like 3 / 4 is shown as -1 (in Green) and 5 / 3 (in Red) is shown as  +2. We do the math anyways in our heads, and the number we really care for is whether the housing is at its limit or not.

**Comment by SpaceOgre** [comment]
I plan on looking into this once #280 is pulled (or rejected). Is this the correct limits?:
* Anything over limit
** Color: Red
** Number: -1, -2 etc
* On limit
** Color: Orange
** Number: 0
* Approaching limit (Is it always 1 from max?)
** Color: Yellow
** Number: +1
* Under limit
** Color: Green
** Number: +2, +3 etc

**Comment by Nutzzz** [comment]
I believe this is how it works:

0 growth
Color: Red
Number: <= -5

-75% growth
Color: Orange
Number: -4 >= and >= 0

-50% growth
Color: Yellow
Number: == +1

Full growth
Color: Green
Number: >= +2

**Comment by SpaceOgre** [comment]
@Nutzzz This seems like it would be correct. Will use this if no one else have other information about it.

**Comment by bolbass** [comment]
As for me I don't like to see the result of this issue. When I see +2 for example I can't see if it's 1/3 or 2/4. The difference between 1/3 and 2/4 that when we have 2/4 we can start creating one more district so I think it's important to see it faster. And I don't think that someone really does the math when he sees housing as 2/4 or 2/11. What the difference? The main thing is to know if the city can grow up or not. So for me it would be more useful to see it like it was before :) And four types of colores as it's already done solve this issue enough I think.
