### ISSUE TITLE
Skip the first cookie-cutter narration block in the loading screen

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#26]
If anything it needs to be done for our own sanity. The amount of times I've listened to Sean Bean talk about the stone age is well beyond a healthy threshold

**Comment by RatchetJ** [comment]
I think this is going to be another one of those ones that will have to wait until modding front end files starts working all the way. It would be another edit in LoadScreen.lua I think.

**Comment by chaorace** [comment]
This has been effectively resolved in the latest patch. Closing!
