### ISSUE TITLE
Changing a cities production queue?

### ISSUE THREAD

**Issue by jharker37** [chaorace/cqui#266]
Could you please tell me how I can change a cities production queue? Ever since I have installed CQUI I haven't been able to select a city and change the queue, only when then last thing that I selected has been finished!

**Comment by chaorace** [comment]
What other mods have you installed?

**Comment by jharker37** [comment]
Thanks for the response! I managed to figure out that the Production Queue mod was what was causing the problem. I should have just realised that it was at least one of the mods causing the problem... The current mods are: Better Trade Screen v3.0, Detailed Worlds and Diplomatic Total.

**Comment by chaorace** [comment]
There's already a version of better trade screen included in cqui, some of
your issues may be caused by having both installed at once

**Comment by jharker37** [comment]
Thanks for info! I'll try a new game(s) without Better Trade Screen v3.0. I have to say CQUI is an awesome mod! Sláinte!
