### ISSUE TITLE
Resource icons

### ISSUE THREAD

**Issue by AndrewMorris-UNT** [chaorace/cqui#268]
Great mod! However, the first games I've played with it active have two-to-four icons for a single resource. Is this a known bug, or something on my end? It's really distracting to have say iron but then also have niter, uranium, and copper icons as well. I can post a screenshot if it helps.

**Comment by SpaceOgre** [comment]
This is addressed in this issue: #180 (Fixed in Pull request #181)

**Comment by chaorace** [comment]
In other words, the best way to solve this issue is updating CQUI to the latest nightly. If you're still having issues, consider checking if your game install is up to date or if another mod you've installed is introducing any incompatibilities

**Comment by AndrewMorris-UNT** [comment]
Cheers! I'll try the nightly; CQUI is the only mod I'm running currently.
