### ISSUE TITLE
New game doesn't load with latest nightly

### ISSUE THREAD

**Issue by Lctrs** [chaorace/cqui#272]
Hi,

With the latest dev-master, whenever I try to start a new game, it got stuck in the loading screen.

Is there some logs somewhere I can send you to help understanding what happen ? Can it have something to do with the fact that I have the game in French and there are no translation for the french language in your mod (yet) ?

Thanks.

**Comment by Lctrs** [comment]
Could also be related to the wrong opening tag at https://github.com/chaorace/cqui/blob/master/cqui.modinfo#L35

**Comment by chaorace** [comment]
Are you still having this issue? I find it strange that it would only not work in French! Has changing that bad tag locally fixed the issue for you?

**Comment by Lctrs** [comment]
Last time I tested few days ago (with a manual fix for the bad tag opening), the issue was still present.

First time I tested, I also remember having tested your mod with the game in english without success.

**Comment by Lctrs** [comment]
I'll retest tonight with the lasts merged PRs.

**Comment by Lctrs** [comment]
Still doesn't work with game in french. I tested with fixed opening tag and full translation in french (for those that are missing from #273, I just copy/pasted the english translations and changed the language to fr_FR).

**Comment by chaorace** [comment]
That's frustrating... let me see if I can get the game to start in French

**Comment by chaorace** [comment]
I've changed my game language to French and successfully loaded a new game in the latest nightly

![](http://i.imgur.com/pDswMBe.jpg)

I am unsure of how to proceed here, since I was unable to replicate. I trust that you're competent enough that it's not just some mod conflict and that the mod is properly installed. If it's not a version conflict, then all I can recommend is deleting CQUI and redownloading it and possibly also checking game file integrity in Steam

**Comment by Lctrs** [comment]
I just thought of one thing : I bought the Gold edition, which means I have all the additional officials DLCs that came after the release of the game. I'll try tonight with a vanilla version of the game and let you know.

Besides of that, your mod is the only one I tried to install, and everytime I try to install it, I erase the previous directory and copy/paste the new one.

I'll check the game file integrity, and also try with a fresh config directory.

**Comment by chaorace** [comment]
I have the digital deluxe edition installed, this is what my DLC directory looks like:
![](http://i.imgur.com/Ip3pBvo.png)

**Comment by Lctrs** [comment]
Oh. I installed mine in the Mod directory in `%appdata%`. I'll try install it in the main DLC directory.

**Comment by Lctrs** [comment]
Houray ! Installing the mod in the main DLC directory did the trick. Thanks ! I can review my translations now.
