### ISSUE TITLE
Citystate name "Palenque" missing

### ISSUE THREAD

**Issue by CrystalDave** [chaorace/cqui#275]
![civ_6_cqui_error](https://cloud.githubusercontent.com/assets/1232245/22322249/7a31b8b2-e34f-11e6-9afb-12c5555627de.PNG)

This is on the current tip of master, English language, no other modifications enabled.

**Comment by chaorace** [comment]
I have absolutely no idea why that may be happening... Could you provide a save to lessen the trouble of trying to create a save with Palenque in it?

**Comment by CrystalDave** [comment]
Here we go: https://www.dropbox.com/s/tgd2ziakq128mr1/AutoSave_0011.Civ6Save?dl=0 (Dropbox since GitHub doesn't support the CivSave filetype)

**Comment by chaorace** [comment]
Couldn't replicate in the latest nightly

![](http://i.imgur.com/bf2sVBd.jpg)

No idea what could have caused that, but it doesn't seem to be CQUI
