### ISSUE TITLE
Improve Smart Banner appearance

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#28]
Here's how the Smart Banner looks currently:

![](https://camo.githubusercontent.com/bbd65a6df072c5f14c661e87c8b204cec36e4866/687474703a2f2f692e696d6775722e636f6d2f7749483946784e2e6a7067)

There are two major issues with the current implementation:
- These banners are too wide! There should be a second row just for smart icons that intelligently hides when there are no icons to display. This way banners are less obstructive and we can attach controls to the sides of the banners more easily without asking the user to make big mouse movements to select them
- The growth/amenities/bordergrowth info baked into the banner is too small. Compared to the other UI elements you kind of need to squint to read it, which isn't good if you're trying to make information easier to access!

**Comment by jacks0nX** [comment]
Would probably be pretty neat if the food/culture growth could have a progress bar analogous to the one for city/wall health. Makes it way easier to see at first glance. Also the correct color should be used, not just "green for everything".

**Comment by chaorace** [comment]
The problem with progress bars is that they're just not as useful as a raw number in this situation. Percentages are good for things that scale, like health/strength and combat. Numbers are better for things that don't scale, like time. 2 turns is always 2 turns, 50 health is NOT always 50 health, it will depreciate in value over time and simply becomes confusing compared to a percentage display like a bar.

As for the building icons, I'm fine with getting rid of them. I've never found them useful and they're actually pretty annoying. I like keeping the district icons though

**Comment by chaorace** [comment]
Addressed in 0b7aa8fc93f3afadd1d55207b3575b5a652ba047 and 00e65cee00f41a180f09acd0c615fc63f8bda4ed
