### ISSUE TITLE
CQUI missing when I reload a game. -Mac-.

### ISSUE THREAD

**Issue by Theox0110** [chaorace/cqui#284]
Hello, once I start a new game, the mod works wonderfully, the problem is when loading the game again, the mod corrupts itself; I am not allowed to build districts, the production queue does not work, etc.

I have tested both versions of your mod on my Mac, Win and Mac, disabling the YnAMP mod, without success.

In any case, great work, I will keep an eye on the updates.

CIV 6 1.0.0.56

Thanks!

**Comment by chaorace** [comment]
Could you provide a save file please?

**Comment by chaorace** [comment]
By "both versions" do you mean v0.5 and v0.6? If so, neither of those work with the latest release (as is noted in large, **bold** letters on the very top of the release page). You'll have to download the latest nightly from [here](https://github.com/chaorace/cqui/archive/master.zip)

**Comment by chaorace** [comment]
I'm closing this issue for now until there's a response

**Comment by Theox0110** [comment]
About both versions, I mean the two ways to install (sorry), via Mods folder or via Show package contents. I deleted my games, but now I start another one to will send you.
Sorry for my english.

**Comment by Theox0110** [comment]
Not sure, (I don't find the version in the readme file), the last one 0.6.
Attached: two screen captures, new game and the same game re-loaded. Saved file
My game is in Spanish.
![after](https://cloud.githubusercontent.com/assets/25484656/22592242/081a1a96-ea19-11e6-80f4-1631ad8b9140.png)
![before](https://cloud.githubusercontent.com/assets/25484656/22592243/081e4da0-ea19-11e6-86df-b813955e7920.png)

**Comment by chaorace** [comment]
[Try this version](https://github.com/chaorace/cqui/archive/master.zip)

**Comment by Theox0110** [comment]
Installed inside Show pack. contents / assets / DLC
Same problem. I will try via Mods folder, uninstalling this one on DLC folder.
![Uploading after 2.png…]()
![before 2](https://cloud.githubusercontent.com/assets/25484656/22592701/4cfbba1e-ea1b-11e6-9de6-0f1079ed8710.png)

**Comment by Theox0110** [comment]
![after 2](https://cloud.githubusercontent.com/assets/25484656/22592864/04f09482-ea1c-11e6-9518-326dedf1561f.png)

**Comment by Theox0110** [comment]
Thank you very much for the help, I will keep tuned on the updates

**Comment by chaorace** [comment]
Could you include a save file please?

**Comment by Theox0110** [comment]
yep. zip file with these two examples.
[cqui saved files test.zip](https://github.com/chaorace/cqui/files/750575/cqui.saved.files.test.zip)

**Comment by Theox0110** [comment]
Civ 6 1.0.0.56 + 3 DLC (Vikings, Polish, Aztecs)

**Comment by Jockss** [comment]
I have a similar issue. When i load a game the options menu for CQUI (the icon at the minimap) dissapears, and I can no longer toggle mini map size et cetera. Do you need a save file? Love your mod btw.

**Comment by chaorace** [comment]
@Jockss Sure, feel free to drop a link here

**Comment by chaorace** [comment]
@Theox0110 

There's at least 4 mod incompatibilities just looking at your save file:
* Better Trade Screen (already included in CQUI)
* Production Queue (already included in CQUI)
* Pusperk's UI Mod
* Unit Report Screen (already included in CQUI)

I'm gonna be honest, you have 20+ mods loaded and I can't help you sift through them all

**Comment by Theox0110** [comment]
@chaorace ops, ok, I will do tests to find incompatibilities. thanks a lot. cheers.
