### ISSUE TITLE
German translation broken

### ISSUE THREAD

**Issue by frytom** [chaorace/cqui#290]
There must have been occured a merging mistake while integrating the german localizations into master CQUI_Text_Settings.xml

because if I use the new merged master CQUI_Text_Settings.xml the german localizations are not shown.
The CQUI-menu is shown in basic english.
Only if I replace the master CQUI_Text_Settings.xml with my own file, which has the added german localizations integrated by myself (see attach file), the CQUI-menu is shown in german.
[CQUI_Text_Settings.zip](https://github.com/chaorace/cqui/files/748427/CQUI_Text_Settings.zip)

You can try it for yourself, choose german text in option, then look into the CQUI menu.

**Comment by chaorace** [comment]
Yep, after some investigating I've found a duplicate line near the end of the Polish translation that broke every LOC string that went after it, which is basically just the German LOC. I've isolated the issue and will be pushing a fix shortly
