### ISSUE TITLE
Production queue: Problems with Corps/Army & Fleet/Armada

### ISSUE THREAD

**Issue by SpaceOgre** [chaorace/cqui#297]
When ever i build Corps/Army & Fleet/Armada the production queue is "empty" but it is still building the unit.

![image](https://cloud.githubusercontent.com/assets/381657/22625410/ef879d7c-eb95-11e6-90a2-c8a2cf334ef9.png)

**Comment by JHCD** [comment]
With the current nightly _19.02.2017 7:50pm_ it's still buggy...

1. I have still the same problems like above, when I'm adding Corps to the queue.

2. When I have infantry corps in production, the right city view will not open:
![error_open_cityview](https://cloud.githubusercontent.com/assets/12496340/23181158/2bf6f0e2-f874-11e6-8db5-fc346eba48fb.jpg)

3. When I open the city view in another city and change to a city with an infantry corp, the Queue won't show the correct Queue:
![error_production_queue](https://cloud.githubusercontent.com/assets/12496340/23181239/822b378e-f874-11e6-80ea-8c84dac723d0.jpg)

At the moment it looks like an _Infantry Corp_ problem. Other units, like _Artillery Corp_ works fine in the current game. But I had the problem at irregular intervals in the past too. So I have to pay attention for it now.

**Comment by SpaceOgre** [comment]
Seems weird to only affect one type of Corps but will look into it.
