### ISSUE TITLE
Trade routes to Egypt shows gold on two rows

### ISSUE THREAD

**Issue by SpaceOgre** [chaorace/cqui#298]
When sending a trade route to Egypt the "extra" gold and food from Mediterranean's Bride is shown on a second row in the panel, but it is already included in the total and thus you can be fooled to think that you would get two more of each.

Missed to take a screen shoot will update when I remember.

**Comment by chaorace** [comment]
Probably some weird line wrapping issue. I'll look into a solution, but this one mostly falls into @Astog 's ballpark

**Comment by astog** [comment]
@SpaceOgre That is probably the yield the destination city gets. In v3.1 the _Make Trade Route_ screen shows both the origin and the destination city yields.

**Comment by SpaceOgre** [comment]
@astog Ah, yeah that could be it.
Will check this the next time I send a trade route to Egypt.

**Comment by SpaceOgre** [comment]
It was as @astog said, my bad :/
