### ISSUE TITLE
Possible cause of game crash

### ISSUE THREAD

**Issue by razvan-panda** [chaorace/cqui#30]
I think the mod might be the cause of 2 type of crashes I had recently (had no crashes before installing it).

One of the game crashes happened after pressing end turn (~ turn 161) and it just quit the game without any error message.

Here is a link to the game save which causes the crash on my computer: https://dl.dropboxusercontent.com/u/25584776/quicksave.Civ6Save

I don't know where to look for crash logs so I hope this save file might be useful for figuring out if the mod was the cause of the crash. This mod and the default Aztec mod pack were the only mods running during that game.

The other crash happend with a city located right on the left border of the map in the upper left corner. Whenever I entered that city with my unit to conquer it the game would just exit to desktop. I'll see if I can find a save for that.

The crash happens with current last version of the mod also.

**Comment by chaorace** [comment]
That's a pretty big deal, I'll start testing the save right away to see if I can replicate. I get the feeling that this may be due to the popup queue not being handled properly when they're disabled, were you playing with or without popup visuals enabled? As far as personal experience goes, I have a ~130 turn game going on started with the mod and I've suffered no instability. Just out of curiosity, how much RAM does your system have?

**Comment by razvan-panda** [comment]
Where do I find the setting for the pop-up visuals? My system has 16 GB of RAM.

**Comment by razvan-panda** [comment]
These are the game executable stats before pressing end turn button: http://i.imgur.com/J92QobF.png

**Comment by razvan-panda** [comment]
Is there any way to disable an existing save from requiring the mod to load? Just to see if it would crash without it. Since this is only an UI mod there should be no reason for it to always be loaded (required for a save to load).

**Comment by chaorace** [comment]
I believe there's a way to do it using firetuner from the civ 5 sdk

**Comment by razvan-panda** [comment]
Are you able to reproduce the issue on your machine? I don't even know if saves load across different machines or operating systems.

**Comment by chaorace** [comment]
Yes, I just tested the savefile and it crashes after ending the turn. I'm going to attempt disabling the mod file now and trying again to see if that affects the outcome

**Comment by razvan-panda** [comment]
Cool, I'm glad it can be reproduced. I tried going back a few autosaves to see if maybe it will not crash when reaching same point but it still crashed.

Hmmm, I seen the Tuner option in the game settings but no idea how to use it once enabled.

**Comment by chaorace** [comment]
Alright, after taking a few stabs at getting the game to disable the mod in your save, I've found no success. That's rough, but I've got no real docs to work with here.

Instead, I've created a dummy version of my mod that the game will accept, but doesn't actually load any files on top of the base game. This is effectively the same as removing the mod. The game still crashes when the turn is passed, even when there's absolutely zero trace of the mod. 

That being said, this kind of all points to it not being the mod's fault, unless it's somehow had some kind of persistent detrimental effect upon your save

**Comment by razvan-panda** [comment]
I think you are right, it might not be the mod. I searched for the previous save which had the crash issue when conquering the city and at that point I did not have the mod installed, it crashed with no mods except aztec. Seems like a bug in the game itself. I'd forward the bugged saves to the devs if I'd knew where to do that.

Thank you for your investigation.

**Comment by razvan-panda** [comment]
Ah, did you also clear the cache folder after using the empty mod replacement? I think there might be some settings that might interfere if `C:\Users\Razvan\Documents\My Games\Sid Meier's Civilization VI\Cache` is not cleared

Would it be possible to give a link here with the empty replacement mod so I can try too? (might be useful to test bug causes for other mods too later)

**Comment by chaorace** [comment]
I've cleared my cache and attempted to pass again with the stubbed mod, still crashed for me.

Here's [the link to the stubbed mod files](https://drive.google.com/file/d/0BzRHuYM0ypGod3BtQ0JzTFpxQ00/view?usp=sharing) so you can try yourself

**Comment by chaorace** [comment]
Oh by the way, the file manifest is the part that's stubbed, I just left the files in because it didn't matter. If the files aren't listed in the *.modinfo manifest they might as well not exist. I confirmed the files weren't loaded in-game by checking menus like the GP Panel to see if they were Vanilla or CQUI (they were the vanilla when checked, confirming the in-game behavior was not being overridden)

**Comment by jacks0nX** [comment]
The only persistent efefct I could imagine would be the custom map pins that I implemented. Have you used those district map pins by any chance?

**Comment by razvan-panda** [comment]
@jacks0nX Yes, I did use map pins to plan where to place districts and deleted some if not most of them as I placed districts. But I did not place the pins with the new icons since in that mod version the new icon pins were not there yet.

**Comment by razvan-panda** [comment]
I checked the save, at that point of the game all the pins added have been removed.

**Comment by chaorace** [comment]
Alright then, I'm going to leave this issue open for a little while longer while you test, but I am going to be removing the bug tag and setting it as invalid for now since it seems to be mostly resolved. Normally I'd wait until I had full confirmation, but I need to get to sleep and I don't want this sitting at the top of the bug tracker with a scary bug tag still on it for the next 8 hours

**Comment by razvan-panda** [comment]
I tested with the stub mod after deleting cache. It's ok to close it as it is most certainly not caused by the mod. Thank you

**Comment by chaorace** [comment]
Alrighty then, sorry about the loss of that save file, it looked pretty fun! Thanks for being so helpful in investigating, reports like yours are the gold standard and I'll never not appreciate receiving them. Have a pleasant day!

**Comment by razvan-panda** [comment]
I am really glad that the issue was not caused by this mod as I already got used to how much easier it makes gameplay and was dreading not using it just to not get a bug again. Thank you for your work on it
