### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by CartesianBear** [chaorace/cqui#301]
The Linux version was released today: 1.0.0.56 (145503).  I installed CQUI into:

`~/.local/share/Steam/SteamApps/common/Sid Meier's Civilization VI/steamassets/dlc`

It shows up in the list of mods, but doesn't seem to have an effect on the game.

**Comment by chaorace** [comment]
Oh boy, this sounds like a can of worms and a half... I'll look into mods on Linux and see what might be stopping CQUI from working in Linux

**Comment by DavidGasku** [comment]
Path names in linux are case sensitive. It's the first thing we should check. I'll take a look at it.

**Comment by DavidGasku** [comment]
yep, that's it. You can quick fix the cqui folder, lowercasing all files recursively (use at your own risk, but please, make sure you are in the correct folder ;)
`find . -depth -exec rename 's!([^/]*\Z)!uc($1)!e' {} +`

What could be the permanent solution, I don't know. Maybe just put a line in readme, explaining the fix.

**Comment by CartesianBear** [comment]
A permanent solution could be to rename all the files in the repository to lowercase.  That shouldn't break either MacOS or Windows, as they are case-insensitive.  Though, someone should test it on both platforms before doing anything.

**Comment by chaorace** [comment]
Are all of the file names lowercase in the linux version? It's strange to me that the file naming convention would change just for Linux, but if that's the case I have no issue just lowercasing everything

**Comment by DavidGasku** [comment]
The filenames are, but not the paths in modinfo file, so I guess the program lowercase the paths in the code. I attach the aztec mod from linux, in case you have any doubt.

[aztec_montezuma.zip](https://github.com/chaorace/cqui/files/776562/aztec_montezuma.zip)

**Comment by rinfiyks** [comment]
The workaround I used was to download the nightly and use `unzip -LL` (lowercase extraction)

**Comment by chaorace** [comment]
Tentatively closed, I'm going to need someone with an actual full graphical linux + steam install to test this and confirm it's actually fixed

**Comment by bulldog98** [comment]
So I tested it, and it worked like a charm until I had to save and reload, then nothing worked in the save I was not able to move via arrow keys and was not able to open the menu, not sure what the problem is.

**Comment by madjestic** [comment]
Works, thanks!
