### ISSUE TITLE
Size of minimap isn't correct after reload the (save-)game

### ISSUE THREAD

**Issue by JHCD** [chaorace/cqui#304]
Hi,

there seems to be a bug in the minimap size implementation.

After reloading a game (continue or loading a savegame) the size of the minimap is wrong.
The cqui settings shows the correct value (f.e. 400), but the minimap size is different (f.e. 512 instead of 400).
Changing the size to a different value and back again - Civ will use the correct size for the map until I reload the game/savegame.

First 	assumption was that its a problem with the in-game-implementation, so I have changed the value in the _CQUI_Settings.sql_ too -> same problem.

Version: Civ VI 1.0.0.56

Regards,
Jens

**Comment by chaorace** [comment]
I've got a fix ready on my local repo that I'll be pushing out later today. Thanks for the report 👍
