### ISSUE TITLE
MiniMap Not Shrinking on Right Click

### ISSUE THREAD

**Issue by Chickerwings** [chaorace/cqui#305]
Love the mod, and the first game I fired it up for worked fine, but since then I've had this issue. Just as the name says.  When I right click on the minimap, the cursor is actually clicking on the game board below the map and will move my units.  Click not registering on the mini-map so I'm stuck in "large" mode.  

List of mods I'm using below:
![image](https://cloud.githubusercontent.com/assets/25777655/22945214/a40762f2-f2b0-11e6-8659-b427ec1cb77b.png)

**Comment by chaorace** [comment]
I suggest trying the minimap size option in the mod menu:

![](http://i.imgur.com/7lOPQFW.png)

It's accessed by clicking the purple icon on top of the minimap
