### ISSUE TITLE
No ability to make faith purchases

### ISSUE THREAD

**Issue by Chickerwings** [chaorace/cqui#306]
I really like most aspects of CQUI, but I've yet to figure out how to make faith purchases.  I'm using a nightly version, most recently downloaded on 2/13/17.  In the upper right of my production list, there is no option to switch between production, faith, and gold purchases.  The gold purchases appear inline with the production options (which is cool, but different than what your screenshots show) and an option for faith purchase never appears even after having the correct buildings/founding a religion. List of mods I'm using below, please let me know if you need any additional info. 

![image](https://cloud.githubusercontent.com/assets/25777655/22945390/5647d4c4-f2b1-11e6-9b59-576be8fa5dc4.png)

**Comment by chaorace** [comment]
I'm unable to reproduce your issue. Here's a picture of it working:

![](http://i.imgur.com/dPowzKc.png)

Remove Unit Report Screen (it's already in this mod) and YnAMP (it's been known to cause issues with some map types). Aside from that, all I can suggest is trying to disable your mods one at a time until you find the culprit
