### ISSUE TITLE
Bankruptcy negative amenity

### ISSUE THREAD

**Issue by ricanuck** [chaorace/cqui#308]
I see a -1 under bankruptcy in the city screen even if I have 100+ gold and positive GPT. Bug?

**Comment by ricanuck** [comment]
Yeah, small bug:

Line 478 should be:
[code]
--Bankruptcy
  CQUI_BuildAmenityBubbleInstance("ICON_NOTIFICATION_TREASURY_BANKRUPT", -data.AmenitiesLostFromBankruptcy, "LOC_PEDIA_CONCEPTS_PAGE_GOLD_4_CHAPTER_CONTENT_TITLE");
[/code]

**Comment by chaorace** [comment]
Neat, I'll go fix this
