### ISSUE TITLE
Missing legacy bonus if UI upscaling is enabled

### ISSUE THREAD

**Issue by JHCD** [chaorace/cqui#312]
Hi Chaorace,

with video option _UI Upscaling_ enabled, you haven't access to the legacy bonus.
I think that's the reason for the _My Government_ tab in the original game.

![ui-upscaling_enabled](https://cloud.githubusercontent.com/assets/12496340/23169111/c8626f30-f84a-11e6-8385-2889c7a1fc5d.jpg)

Is it possible to bring back the tab when _UI Upscaling_ is enabled?
Or to build in a scroll bar?

Thx,
Jens

**Comment by chaorace** [comment]
Duplicate of issue #96

Upscaling is generally a low priority feature in terms of support, but I do plan to revisit issues like #96 and #3 at a later time
