### ISSUE TITLE
Still the Name Problem, no pancil to change City Name

### ISSUE THREAD

**Issue by croshy** [chaorace/cqui#319]
You wrote:
"Top of the left panel. It has a pencil in it"

Sorry to disturb again but i can not see a Pancil for Name Change in the Modded UI, just the Name. There is no Pencil on your Picture in top let aswell:

https://camo.githubusercontent.com/e39306c882c0f9b95494ea391cee0baa838d3072/687474703a2f2f692e696d6775722e636f6d2f583571427a6a612e6a7067

**Comment by chaorace** [comment]
Please post in the existing issue (#317)instead of creating a new one when I close the original. I'll still respond to you, it's just a label for the sake of organization. I've posted my reply to your issue there
