### ISSUE TITLE
Report tabs can become desynched

### ISSUE THREAD

**Issue by JHCD** [chaorace/cqui#321]
Small dinky funny bug... ;)
Open Reports, change report tab (f.e. Units) and than select _Hide Buildings_.
Report changed to _Buildings_ but the **old** tab is highlighted furthermore. 

![error_reports](https://cloud.githubusercontent.com/assets/12496340/23251171/8ced80d0-f9ac-11e6-9eca-8f9e733a725a.jpg)

**Comment by chaorace** [comment]
This is a pretty old bug in Unit Report Screen. I think it might actually be fixed in the latest version, but that's not yet in CQUI. I'll look into sourcing that update to fix this issue
