### ISSUE TITLE
Australia Patch incompatibility

### ISSUE THREAD

**Issue by emperorfool** [chaorace/cqui#323]
I started two games today using a nightly release from about a week back and the Australia patch. In both, the UI disappeared about 50-100 turns in when I hit next turn. I reloaded then restarted, and both times the UI disappeared after hitting the next turn button.

**Comment by chaorace** [comment]
Why would Firaxis drop the patch at 11PM right before Friday 😢. I guess I know what I'm doing all tonight and tomorrow!

**Comment by emperorfool** [comment]
Yeah, I saw the Australia video and tried to play it yesterday, but it wasn't there. I started a game today and didn't even notice the patch had dropped until the UI disappeared and I saw the alert on the main menu after restarting.

**Comment by thejase** [comment]
This happens about 20 turns into the American patch.  It coincided with me meeting the first other civilization.  I didn't receive a "hello" video from them, but I got the policy boost.

**Comment by chaorace** [comment]
Welp, it's been three hours and I think I've squashed all of the incompatibilities introduced in the Australian patch. Try downloading the latest commit and letting me know how it works for you guys!

**Comment by chaorace** [comment]
Gonna close this for now since nobody seems to have complained yet!

**Comment by JHCD** [comment]
Upgrade Units in the _Unit Report Screen_ doesn't work with the new Australia patch:

Unit Report Screen:
![error_unit_upgrade](https://cloud.githubusercontent.com/assets/12496340/23325263/79ac60b0-faf4-11e6-9ca4-5a0ece4b6acf.jpg)

Upgrade is possible:
![unit_upgrade_possible](https://cloud.githubusercontent.com/assets/12496340/23325286/9816a16e-faf4-11e6-8453-5780f81273be.jpg)

**Comment by JHCD** [comment]
@chaorace 
Do you reopen this issue or shall we open new issues for every bug for a better overview?

**Comment by chaorace** [comment]
@JHCD The Unit Report Screen is a separate mod from CQUI that we include with their permission. I consider this a URS bug and therefore it deserves its own topic. I've created an issue on your behalf in #340
