### ISSUE TITLE
New districts don't show up in the city build list if the city view is open with SHIFT

### ISSUE THREAD

**Issue by perseghini** [chaorace/cqui#33]
- Astronomy research complete
- Open a city with SHIFT key (Enhanced binding)
- Holy Site District not in the city build list
- Close the city view (Right Click)
- Open the city again but through clicking on its name instead of SHIFT
- Holy Site District is now in the city build list
- Then reopen the city view with SHIFT key, and now the Holy Site District is here.

(I guess the refresh city build list is not refreshed with SHIFT ?)

**Comment by chaorace** [comment]
Thanks for the heads up, I'll start looking into it

**Comment by perseghini** [comment]
I don't want to make a pull request for this but changing this:

```LUA
if( uiKey == Keys.VK_SHIFT ) then
   if(CQUI_cityview) then
      LuaEvents.CQUI_CityviewDisable();
      UI.SelectNextReadyUnit();
   else
     LuaEvents.CQUI_CityviewEnable();
     LuaEvents.CQUI_GoNextCity();
  end
end
```
to that :

```LUA
if( uiKey == Keys.VK_SHIFT ) then
   if(CQUI_cityview) then
      LuaEvents.CQUI_CityviewDisable();
      UI.SelectNextReadyUnit();
   else
     LuaEvents.CQUI_GoNextCity();
     LuaEvents.CQUI_CityviewEnable();
  end
end
```

seems to fix the issue. I didn't test it a lot, and I only had one city (so GoNextCity() stayed on the same city..)
so you might need to tweak it a bit and test it more.

Hope, it helps !

Cheers.

**Comment by chaorace** [comment]
Yes, that seems to have done it, I'm commit this change now. Thanks!
