### ISSUE TITLE
Cityview breaks occasionally in German, Korean, and Polish

### ISSUE THREAD

**Issue by JHCD** [chaorace/cqui#331]
As I had written in #297 the cityview is partial in irregular intervals.
Now I have such a situation: no military units in production, but in every city only the left part is shown.
The right part is shown for a short time and closed immediately.

![amboise_citiview_partial](https://cloud.githubusercontent.com/assets/12496340/23308671/370567cc-faac-11e6-9316-84f8dd2fa0be.jpg)

After pressing _Next Round_ the error exists furthermore.
I had to reload Civ to get a whole cityview again.

Restart game and load the savegame at the same position will not reproduce the problem.

Here is the correct view at the same round like the error above:

![amboise_citiview](https://cloud.githubusercontent.com/assets/12496340/23309326/93f1c582-faae-11e6-91a3-3a5824ee2514.jpg)

**Comment by JHCD** [comment]
I have found some errors in the Lofgiles:

Lua.log:
>Runtime Error: C:\Users\Jens\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\UnitFlagManager.lua:187: attempt to index a nil value
stack traceback:
	C:\Users\Jens\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\UnitFlagManager.lua:187: in function 'CQUI_HidePath'
	C:\Users\Jens\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\UnitFlagManager.lua:1195: in function 'OnUnitSelectionChanged'
	[C]: in function 'func'
	[C]: in function '(anonymous)'

Database.log:
>[1891194.858] [Localization] ERROR: UNIQUE constraint failed: LocalizedText.Language, LocalizedText.Tag
[1891194.858] [Localization]: While executing - 'insert into LocalizedText('Tag', 'Language', 'Text') values (?, ?, ?);'
[1891194.858] [Localization]: In XMLSerializer while inserting row into table insert into LocalizedText('Tag', 'Language', 'Text') with  values (LOC_CQUI_UNITS, pl_PL, Jednostki, ).
[1891194.858] [Localization]: In XMLSerializer while updating table LocalizedText from file cqui_text_settings.xml.
[1891194.858] [Localization] ERROR: UNIQUE constraint failed: LocalizedText.Language, LocalizedText.Tag

Localiziation.log:
>[1891192.788] Warning: ICU: A resource bundle lookup returned a fallback result (not an error)
[1891206.109] ERROR: Missing argument 1. ({1: plural 1?Bonus; 2?Bonusse; other?Bonusse;})
[1891206.109] ERROR: Failed to evaluate parameter 1. {1: plural 1?Bonus; 2?Bonusse; other?Bonusse;}

I hope that could help...

**Comment by JHCD** [comment]
Runtime error in Lua.log occurs regulary and independent of cityview problem...
Moved to issue #332

**Comment by chaorace** [comment]
Ah, it seems like there's a bug in the Polish translation. I'll see about correcting that for you 👍

**Comment by JHCD** [comment]
Hi Chris, I'm playing in German, **not** in Polish ;)

**Comment by chaorace** [comment]
Ah, based on this line I assumed it was Polish:

` (LOC_CQUI_UNITS, pl_PL, Jednostki, )`

I remember this being an issue once before. A typo in a translation breaks any language that comes after that typo, even if it's not the same language. (that means this bug also affects German and Korean)
