### ISSUE TITLE
Errors thrown when consuming units

### ISSUE THREAD

**Issue by JHCD** [chaorace/cqui#332]
Missing Exception Handling? ;)

Lua.log:
>Runtime Error: C:\Users\User\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\UnitFlagManager.lua:187: attempt to index a nil value
stack traceback:
	C:\Users\User\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\UnitFlagManager.lua:187: in function 'CQUI_HidePath'
	C:\Users\User\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\UnitFlagManager.lua:1195: in function 'OnUnitSelectionChanged'
	[C]: in function 'func'
	[C]: in function '(anonymous)'

**Comment by JHCD** [comment]
>Runtime Error: C:\Users\User\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\UnitFlagManager.lua:165: attempt to index a nil value
stack traceback:
C:\Users\User\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\UnitFlagManager.lua:165: in function 'CQUI_ShowPath'
C:\Users\User\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\UnitFlagManager.lua:374: in function '(anonymous)'

**Comment by JHCD** [comment]
>Runtime Error: C:\Users\User\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\UnitFlagManager.lua:187: attempt to index a nil value
stack traceback:
C:\Users\User\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\UnitFlagManager.lua:187: in function 'CQUI_HidePath'
C:\Users\User\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Assets\UI\UnitFlagManager.lua:382: in function '(anonymous)'

**Comment by chaorace** [comment]
Yeah, this is a pretty harmless little error that happens whenever you hover over non-civ owned units, like barbs or citystates. It's been a relatively low priority thing for me since it doesn't actually seem to cause any issues outside of polluting the log files

**Comment by JHCD** [comment]
Hi Chris,
sure, it's an unimportant bug, but you're not right.
f.e. one of them is thrown, when you activate the last action  of a workman.

**Comment by chaorace** [comment]
@JHCD Are you sure about that? [Because I can reproduce what I claim to be the root cause](https://drive.google.com/uc?id=0BzRHuYM0ypGoaGFKOUtMWC10SUU). Of course, there may have been two root causes, and if I test after applying your commit, it _does_ fix this bug as well as the one you describe

**Comment by JHCD** [comment]
Great, I hoped so...
That was another reason why I changed _CQUI_ShowPath_ and _CQUI_HidePath_ too and not only _OnUnitSelectionChanged_
