### ISSUE TITLE
OSX: can't open civics tree either by top left icon or in Choose Civic screen

### ISSUE THREAD

**Issue by clay9000** [chaorace/cqui#333]

**Comment by robertseaton** [comment]
Also occuring on Linux

**Comment by lettergram** [comment]
Works if you copy the original civicstree.lua file over the mod's civicstree.lua, going to do a PR shortly

**Comment by chaorace** [comment]
I've reopened the traditional OSX incompatibility thread (#195) once again, since it seems to be that time of year again where Firaxis neglects everything that's not Windows again. Please direct all further conversation concerning this to that thread going forward, thanks!

**Comment by andreipoe** [comment]
Just ran into this issue on Windows. I did what @lettergram suggested and it's now fixed. This is on commit `2328c20`.

**Comment by chaorace** [comment]
@andreipoe What version of Civ 6 are you running?

**Comment by andreipoe** [comment]
@chaorace 1.0.0.56, the Winter Update.

**Comment by Remolten** [comment]
@chaorace 

I'm still running into this issue on OSX. 

Latest Civ version 1.0.4 with CQUI from the Steam Workshop.

**Comment by chaorace** [comment]
@Remolten 1.0.4 is not the latest game version _at all_

**Comment by Remolten** [comment]
@chaorace That is the version listed in Aspyr's game launcher for macOS. I am fairly sure it is the "latest" version, even if it differs (in numbering) from Windows.
