### ISSUE TITLE
URS promotion button doesn't work in Australian Summer

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#340]
[See here](https://github.com/chaorace/cqui/issues/323#issuecomment-282436914) for more info.
I'm waiting to see if URS gets updated soon to fix this minor issue before I try fixing it myself

**Comment by JHCD** [comment]
Error-Msg:
>Runtime Error: [... ]\Mods\cqui\Integrations\URS\ReportScreen.lua:1655: attempt to index a nil value
stack traceback:
	[... ]\Mods\cqui\Integrations\URS\ReportScreen.lua:1655: in function 'sort_units'
	[... ]\Mods\cqui\Integrations\URS\ReportScreen.lua:2083: in function '(anonymous)'

**Comment by JHCD** [comment]
@chaorace 
Commit #386 removed the URS Update.
Please reopen this issue.

**Comment by ProustIdee** [comment]
After looking at that change:
https://github.com/chaorace/cqui/commit/f567b47714dffca2b1fd131b2fd482aed3f6daff#diff-17f084811797af6c379eb7f41fc7ce06

and the previous 1.73 update:
https://github.com/chaorace/cqui/commit/f121bcf1b8a7be7afd2ab855d153bf624bf20f46#diff-17f084811797af6c379eb7f41fc7ce06

I think reverting

`+					if kBuilding.Name == Locale.Lookup( GameInfo.Districts[i].Name ) then
+						iNumDistricts = iNumDistricts + GameInfo.Districts[i].Maintenance
+						break`

and
`+		if ( iNumDistricts > 0 ) then
+			local pBuildingInstance:table = {}
+			ContextPtr:BuildInstanceForControl( "BuildingExpensesEntryInstance", pBuildingInstance, instance.ContentStack )
+			pBuildingInstance.CityName:SetText( Locale.Lookup(cityName) )
+			pBuildingInstance.BuildingName:SetText( "Districts" )
+			pBuildingInstance.Gold:SetText( "-" .. tostring( iNumDistricts ) )
+			iTotalBuildingMaintenance = iTotalBuildingMaintenance - iNumDistricts
+		end`

Would put it back to an operational state? At least if this commit was what broke it.

**Comment by JHCD** [comment]
I will look into it...
