### ISSUE TITLE
CQUI options button in the minimap panel has no tooltip

### ISSUE THREAD

**Issue by paavohuhtala** [chaorace/cqui#347]
Should be fairly straightforward, just add a `ToolTip` property [here](https://github.com/chaorace/cqui/blob/66297ff30dc94f8d22b8b1cc3a8ab1bb661c5dc0/Integrations/ML/UI/minimappanel.xml#L57), and put the localized text somewhere (for instance in [general text](https://github.com/chaorace/cqui/blob/master/Assets/Text/cqui_text_general.xml)).
![civilizationvi_2017-02-26_14-12-47](https://cloud.githubusercontent.com/assets/803180/23339535/c4e50700-fc2d-11e6-8d24-dd39ebaf222a.png)
![civilizationvi_2017-02-26_14-12-43](https://cloud.githubusercontent.com/assets/803180/23339537/c6b42a52-fc2d-11e6-9d0e-900c7770523c.png)

I can implement this if it's the right approach.

**Comment by chaorace** [comment]
This actually did exist at one point, but I decided to remove it (64633d017d127bcf32d4f76da6e0e4417e301a69) since it didn't seem very useful and honestly just seemed like pointless busywork for the translators. I know that sounds like a silly reason, since it's only one line, but one-liners like these add up quickly and I consider this button to be, for the most part, self-explanatory

**Comment by JHCD** [comment]
I don't think so...
After I had installed CQUI the first time I searched a long time for the config... 
It would have been nice if there had been a hint for it.

**Comment by paavohuhtala** [comment]
But does it really have to be translated? It could always say CQUI, or even CQUI Options in all languages. In my opinion the mere existence of a tooltip improves UX and looks better, by making the button behave like all the other buttons. The lack of a tooltip is in my opinion a bigger problem than an untranslated piece of text. The difference in behavior makes the button feel "fake" and tacked on.

Furthermore, since there's no [longer] a tooltip, hovering over the top & bottom parts of the button shows the tooltip for the element under the button (either the minimap or the game world), even when clicking would activate the button. This can be confusing, and doesn't look good. 

![civilizationvi_2017-02-26_19-53-51](https://cloud.githubusercontent.com/assets/803180/23342168/353961a6-fc5e-11e6-95b5-032e3b786c86.png)

It's obviously not a huge issue, but I think little things like this are important for the general quality and "feel" of the UI (which the official UI mostly lacks 😁).

**Comment by chaorace** [comment]
@paavohuhtala Alright, you've convinced me! If you'd like to do the honors, feel free to submit a PR with your change. Otherwise I'll add it myself in your stead

**Comment by paavohuhtala** [comment]
I can probably do it tomorrow, or you can it now if you have the time!
