### ISSUE TITLE
Canceling district placement closes build menu

### ISSUE THREAD

**Issue by ProustIdee** [chaorace/cqui#35]
In Vanilla Civ VI, when you click a district, it "zooms" into the city showing you where you can place it with relevant modifiers. If you right click, it cancels out of the placement menu, but brings you back to the build menu, so you can choose to build something else.

In CQUI, when you click a district, it shows you where you can place it with the relevant modifiers, but when you right click, it cancels out of the build menu. I think it would be better if it brought you back to the default build menu so you can choose to build something else.

**Comment by chaorace** [comment]
Thanks for the report! I'm on it
