### ISSUE TITLE
Relationship score in tooltip of leader icon

### ISSUE THREAD

**Issue by atggta** [chaorace/cqui#356]
Can you add  very usefull enhancement like this?
![image](https://cloud.githubusercontent.com/assets/26062472/23366784/9927775c-fd3a-11e6-8c12-69c5400d3fc7.png)

**Comment by atggta** [comment]
I inserted code in diplomacyribbon.lua. It is not my code, but it's work.
[diplomacyribbon.zip](https://github.com/chaorace/cqui/files/806651/diplomacyribbon.zip)

**Comment by chaorace** [comment]
Now _that's_ a good idea. Yeah, this is going in the mod

**Comment by ricanuck** [comment]
I will work on this in the next few days. I will NOT put it into the tooltip, as I plan to use the tooltip for better things. I will try and put it into the FACE tooltip (you know, the smilies or haties that show the mood of the civ). By the way, if you know a nice face for NEUTRAL (faceless in vanilla), let me know which.

**Comment by ricanuck** [comment]
Added.

**Comment by ricanuck** [comment]
This has been solved, and also added to the diplo view vertical ribbon (useful during negotiations with other civs).
