### ISSUE TITLE
Compress Production Queue Clickables

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#36]
I'm [currently working on this](http://i.imgur.com/FT00iBB.png), thought it was about time I'd put it on the tracker

**Comment by aesir112** [comment]
That looks good, however I'd suggest even more condensed.

**Comment by chaorace** [comment]
I feel it's already starting to get a little difficult to quickly click at the current size. I'll consider the possibility of an even smaller option once we get a proper settings menu ready. This is definitely one of those minor things that would be a pain for the user if they had to reconfigure it every time they loaded the save
