### ISSUE TITLE
Production Queue

### ISSUE THREAD

**Issue by Jamolisim** [chaorace/cqui#361]
I am sorry if this has been answered already but I searched here and did not see a solution.

I cannot choose anything in the production window when I settle my first city.  The button in the button right-hand corner is basically "dead" and does not respond when I choose it.  HELP!

**Comment by chaorace** [comment]
What OS are you using, where did you get your copy of CQUI, and are you currently trying to play a scenario? Also, please provide a save file

**Comment by JHCD** [comment]
I haven't that problem...

**Comment by chaorace** [comment]
@Jamolisim It's been a few days without response now, I'm closing this issue until he comes back to provide more info

**Comment by Jamolisim** [comment]
My apologies.  I removed all the other mods I had, only activated this one, and it worked great!  Thank you!
On Monday, March 6, 2017, 3:39:53 PM PST, Chris <notifications@github.com> wrote:
@Jamolisim It's been a few days without response now, I'm closing this issue until he comes back to provide more info
