### ISSUE TITLE
Oversized header buttons in report screen after Australia Patch

### ISSUE THREAD

**Issue by andydtoma** [chaorace/cqui#366]
Since the Australian Patch, the report screen headers are oversized.
I am playing on a laptop with DX11, and before the patch the headers were ok, in the same configuration.

![image](https://cloud.githubusercontent.com/assets/17074066/23577261/9488c5a6-00ba-11e7-8e15-f1d881acf333.png)

**Comment by JHCD** [comment]
I had it before the Australian Patch to, so it seem's to be an resolution problem...

**Comment by JHCD** [comment]
Looks like the report-screen build proportionally to the resolution during the buttons size is oriented to the longest text and all buttons will have the same size.

Could you try the following thing:
C:\Users\[Username]\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui\Integrations\URS - 

Line 2005:
> kTab.Button:SetSizeToText( 20, 20 );

When thats not enough, try to reduce the value in Line 2055 until 0:
> m_tabs.SameSizedTabs(50);

![urp_tabs_20-0](https://cloud.githubusercontent.com/assets/12496340/23579143/2d1ba1c2-00e7-11e7-857b-8da47e078c58.jpg)

**Comment by chaorace** [comment]
I think this may have something to do with UI scaling. @andydtoma are you using UI scaling?

**Comment by JHCD** [comment]
At my side it doesn't fit on the system where I haven't enabled _UI Upsacling_

**Comment by JHCD** [comment]
Second: The french translation text looks very long compares to the english or german one...

**Comment by andydtoma** [comment]
No, I don't use any scaling. In fact I set up the graphic effects at minimum and I play at FullScreen, with Scaling disabled.
In January I didn't notice any oversized like that. Maybe I missed a commit before the Patch ?
I will try the setting suggested by JHCD and I will let you know.

**Comment by andydtoma** [comment]
OK, setting in line 2077: m_tabs.SameSizedTabs(0); seems to calm down the buttons.

**Comment by JHCD** [comment]
Could be, that the text in CQUI or the UI building with the patch have changed so that's not fit furthermore...
Have you tried _kTab.Button:SetSizeToText( 20, 20 );_? At my side it is enough to fit it into the screen.

**Comment by JHCD** [comment]
@chaorace The two values are from the original game, but with URS we have more Tabs.
I would prefer to reduce the values. If thats okay for you I would do a RP.

**Comment by andydtoma** [comment]
Just SetSizeToText was not enough.

**Comment by andydtoma** [comment]
To summarize what I've done:

1.  I changed in DLC\cqui-master\Integrations\URS\reportscreen.lua :

- In function AddTabSection( name:string, populateCallback:ifunction )
Line 2005 : kTab.Button:SetSizeToText( 20, 20 );

- In function Initialize()
Line 2077 : m_tabs.SameSizedTabs(0);

and I got that:
<img width="608" alt="screenshot 2017-03-05 08 37 39" src="https://cloud.githubusercontent.com/assets/17074066/23585515/592323d6-0181-11e7-9efc-b031921cbfbe.png">

2.  After that, I put back in Line 2005 : kTab.Button:SetSizeToText( 40, 20 );

and I got that:
<img width="618" alt="screenshot 2017-03-05 08 46 20" src="https://cloud.githubusercontent.com/assets/17074066/23585531/a77ba3e6-0181-11e7-97cf-50783ebe84ba.png">

So the only change needed is in the function Initialize !!!!

**Comment by chaorace** [comment]
@JHCD Hey sorry for taking a while to get back to you. That change sounds fine, feel free to submit a PR!

**Comment by JHCD** [comment]
> 2005: kTab.Button:SetSizeToText( 40, 20 );
2077: m_tabs.SameSizedTabs(0);

is the same linke
> 2005: kTab.Button:SetSizeToText( 20, 20 );
2077: m_tabs.SameSizedTabs(20);

So I changed only the value in line 2077 to "0"...

**Comment by Lctrs** [comment]
@JHCD Yeah. Sadly, my english isn't good enough and I tried to stick with vanilla terms for the french translations. So most of it is sadly bigger than ther english counterparts.

@andydtoma If you find some improvements for the current french translations and don't know how to contribute, feel free to open an issue and mention me inside (or else, I'll likely miss it). I'll happily make the corresponding pull request. Thanks. :)
