### ISSUE TITLE
German translation is broken

### ISSUE THREAD

**Issue by JHCD** [chaorace/cqui#367]
Since the polish update (commit #353) the german translation isn't working furthermore...
Sejbr has inserted most of the new text-strings as duplicated entries not instead the old one.
Please revert this commitment...

**Comment by sejbr** [comment]
I'm so sorry. I must have unstaged the deletions somehow and it went unnoticed. I'll PR a fix once I get home in the evening.

**Comment by JHCD** [comment]
Did you not got an eMail for my commitment comment 5 days ago?
https://github.com/chaorace/cqui/commit/62dfccf3d6313bbb336d2e8b858736dce2641641#commitcomment-21069404

**Comment by sejbr** [comment]
I most likely did receive it but I'm subscribed to the whole repo and didn't notice it. I just saw Chris's merge.
Well, my whole week was kinda ****** but no excuses. Won't happen again. I'm not quite sure where my brain was when I clicked unstage on those. Must have been on that sleepless stage of "This line red. No, no good at all *UNSTAGE*"

**Comment by JHCD** [comment]
I used the @ tag to force an eMail to you, but I don't now if it works there.
So I opend that issue...

**Comment by sejbr** [comment]
~~Yeah with whole repo marked as "Watching" there's no particular indication of the @ tag~~
Oh, I see. Apparently, if you're mentioned it's marked with that tiny "important" icon on gmail. I've never noticed that.

**Comment by chaorace** [comment]
This has been fixed in #368
