### ISSUE TITLE
Implement a proper settings menu

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#37]
Currently we use a minimap popout without any persistent settings. We frequently get a lot of small tweak requests that just can't really be squeezed into that menu. Moreover, it's becoming a bit unreasonable to ask users to recheck all of their favorite settings every time they load a save, persistent settings have become a must. Implementing this is key to making the mod more user-friendly and customizable

**Comment by kblease** [comment]
When I am done with the production queue I would love to take this on.

**Comment by chaorace** [comment]
@kblease That would be an incredible boon to the project! Keep me updated if/when you make some headway 👍

**Comment by chaorace** [comment]
I've made some exciting progress on this front! I'm self-assigning this as it is now my personal pet project TO GET THIS DONE
