### ISSUE TITLE
Production panel on city screen gone after loading game

### ISSUE THREAD

**Issue by Karmak0ma** [chaorace/cqui#370]
Hi,

I´ve been having an issue where the right side panel of the city screen is not working after loading a game.
It seems like that part of the mod is not working correctly, because the city info at the bottom has reset to the vanilla non-modded version. Everything else in the mod seems to be working OK.

I can reproduce the issue just by starting a new game, exiting to main menu and loading the auto/manual save.

Here is a screenshot (I opened the left hand side panel manually to show that is working, but selecting a city does not open it)

![screenshot](https://cloud.githubusercontent.com/assets/26208364/23592189/66d38f12-01fd-11e7-93a0-5cfa1ddbb863.png)

I am running on Windows 10 with only this mod installed (plus the official).
I have only installed the mod from Steam, never directly. Tried unsubscribing and subscribing again but no use..

**Comment by Karmak0ma** [comment]
OK, I seem to have fixed the problem.

I unsubscribed from the mod and started a game with no mods installed.
When I hit ESC I saw that Divine Yuri Custom City Panel was there in the mods used list, although it didn't show up in the additional content menu on the main menu.

Anyway, I went to the DLC directory and deleted Yuri Custom City Panel directory manually, and now everything seems to be working again.
I don't think I ever installed Yuri's mod directly (I'm quite sure, but I have a bad memory...) so I think it may have been after subscribing / unsubscribing while I was testing stuff?

Not sure, but I think some other people were reporting the same problem, so it's a place to start looking.

**Comment by chaorace** [comment]
Yuri's citypanel has flags in it that force apply it and hide it from the mod menu. That was a symptom of the very early days of Civ VI modding so chances are it was applied once a long time ago and forgotten about. Thanks for the heads up though!
