### ISSUE TITLE
Show notification for Inspiration/Eureka the turn it reaches max instead of the turn before.

### ISSUE THREAD

**Issue by brianschamel** [chaorace/cqui#377]

**Comment by chaorace** [comment]
It shows 1 turn before because you're basically guaranteed to waste science the next turn unless you hit exactly 50%

**Comment by chaorace** [comment]
I'm going to leave this ticket open for further discussion for another day, at which point, if there's been no convincing argument for changing this behavior, I'll close the ticket

**Comment by brianschamel** [comment]
I guess that makes sense, but the additional science/culture saved isn't much - 5% of your per turn yield, on average, if the civic/tech would take 10 turns with no boost (which of course makes it even less relevant on the slower speeds).

Instead, I would prefer to not have to switch to the tech I just received the boost for each time, which switching off one turn before maximum.  Perhaps one of the in-game options for the mod, similar to how you can enable/disable tech/civic pop-ups?

Ideally, it could stay the way it is, but when you receive the boost, there would be a button on the window that pops up that allows you to switch to that tech right there if it would require a turn of research, but I imagine it wouldn't be possible without .dll access.

**Comment by chaorace** [comment]
You might be surprised to hear, but we could pretty much rewrite the entire UI from day 1. The main reasons we don't do that are the amount of time required and the fact that the vanilla UI is actually quite good in most respects, especially user familiarity. There's also the fact that we _can't_ control how data is organized on the backend, which does present difficulty whenever we want to do something differently (for example, the game presents us with a distinct "unit blueprint" (so to speak) for each way you can acquire it. That means there's actually up to 3 different units presented to the production panel for each real unit (produce, gold buy, faith buy). It's entirely possible to display that data any way we want, but the way that data is hardcoded to be presented to us makes it easiest if we wanted to actually have three separate places to buy a unit based on purchase type, like the vanilla UI. Overcoming formatting like this is often trivial, but can be confusing to look at and has a tendency to never work quite correctly on the first try, even possibly revealing design-flaws in the base game we have no control over)

Anyways, your comment is noted and I'm considering better ways to solve the design problem at hand here. I believe the best method to specifically stop people from letting techs roll beyond the 50% mark isn't a second status message, but possibly a turn blocker (like the kind you get when it's time to pick a new tech). Simply enable the option and the game will physically stop you from ending the turn until you manually acknowledge the fact that continuing to research could waste resources. I'm aware of the fact that it's not uncommon to _want_ this situation and that being forced to navigate a menu pointlessly is annoying, so I'm going to qualify a blocker like that with the following criteria: appears last (that way you can safely right-click to force-end if you see this blocker and don't care), has a "dismiss blocker" button (so new users who don't know about force-skipping can intuitively ignore this blocker), and only appears once per-tech (so you don't need to acknowledge more than once for each tech you brute-force)

What do you think about said solution? Criticism is good, so tell me if what I'm saying doesn't feel like it's solving a problem

**Comment by Sadario** [comment]
I created a fork that changes exactly this (check my repo). Test it if you want.

**Comment by brianschamel** [comment]
I'd definitely only prefer it to happen the way you're describing (having to confirm through a menu) if, when choosing a tech to research, you could choose to either stop at 50 and change (what you are suggesting) or researching all the way without a prompt (like it is now).

I could imagine a few different ways to choose:

1. In the tech selection panel, you could turn the section of each tech that describes the boost into a button that does the halfway research.  I'd imagine this would be the most intuitive 
2. Using a different mouse button when choosing the tech (although I think Shift-Click, Control-Click, and Right Click are all taken in this context, so you might have to have it be something like the middle mouse button, or Alt-Click, though neither option seems tempting).

**Comment by chaorace** [comment]
@brianschamel Noted. I'm going to consolidate this with the #381 now since people don't seem adverse to the idea
