### ISSUE TITLE
Mac AppStore version - new CQUI user problems

### ISSUE THREAD

**Issue by klouseehew** [chaorace/cqui#379]
Hi.  I just started using your mod yesterday after seeing it in use by Quill18.  I have the most recent master download (updated 4 days ago) and most of it seems to be working wonderfully.  Unfortunately, there are 2 rather significant issues I noticed.  First, I cannot open the civics tree.  I click on it and the sound effect is there, but nothing happens.  Tech tree and Great People open fine.  Second, I have nothing but a shadow where the leaders panel should be.  I cannot see any info about them or interact with them at all, unless they initiate it. 

I am using MacOS Sierra (10.12.3) and my Civ6 is version 1.0.2 from the AppStore (fall and winter updates, but not the Australia summer update yet).  The only other addition I have is the Poland DLC.  I started a couple random games and created a game, but the two problems mentioned above persisted.  Thank you for your time and assistance.  I look forward to enjoying the full capability of your mod :)

klouseehew

**Comment by chaorace** [comment]
Please use the link in the description of the Workshop page to download the Mac/OSX version of CQUI from the workshop instead of the main version. It enjoys feature-parity with the main release and works on the older version of Civ that Mac/Linux uses

**Comment by klouseehew** [comment]
Thank you!  That solved it beautifully :)
