### ISSUE TITLE
Shift hotkey for Enhanced interferes with Shift-clicking in Tech or Civic tree

### ISSUE THREAD

**Issue by dubert** [chaorace/cqui#38]
Loving the Enhanced keybinds! Thanks so much for making them.

When using the Enhanced preset, and you shift-click tech tree items, it rapidly toggles the city view in the background.

**Comment by chaorace** [comment]
Ah, I had completely failed to anticipate that little circumstance! Thanks for the report, hopefully it's a simple fix
