### ISSUE TITLE
Fortify until Healed only working for one turn

### ISSUE THREAD

**Issue by dubert** [chaorace/cqui#39]
It's fortifying, but not until healed, it just activates the next turn again. Maybe the id was wrong?

```
if( uiKey == Keys.H ) then
	UnitManager.RequestOperation(UI.GetHeadSelectedUnit(), 2126026491); -- OH MY GOD IT WAS SO HARD TO FIND THAT ID. WHAT WAS FIRAXIS THINKING
end
```

Also I'm kind of surprised you can't do:
`UnitManager.RequestOperation(UI.GetHeadSelectedUnit(), UnitOperationTypes.HEAL)`

**Comment by chaorace** [comment]
I have a hunch that the fortify-until-heal operation breaks whenever a hostile until is nearby, including barbs. Could you try using the fortify until heal hotkey when the unit is completely isolated to help test this?

**Comment by chaorace** [comment]
Yep, just tested it and not working as intended. Welp, back to the depths for me I suppose
