### ISSUE TITLE
Visual Indicator & Airplane List Button - for Airstrip improvement

### ISSUE THREAD

**Issue by JCron245** [chaorace/cqui#396]
Airstrips are hard to find as they seemingly have no label, it would be cool to have something like the airport where you have a button to click on so you can get the full list of airplanes at that spot. 
(I will keep playing with the airstrips, maybe they already do this but I am dumb)

**Comment by chaorace** [comment]
This will be fixed when bug #201 is handled. There's no need to create a new UI for this when we could just fix the one that's been broken
