### ISSUE TITLE
Game crashes when changing minimap size.

### ISSUE THREAD

**Issue by Riskke** [chaorace/cqui#400]
As soon as I drop the slider, game crashes by going to the previous loading screen and then to windows.

 If there's any dumps or log I can share please make me know.

I'll change the default size on the SQL (so I can play) and see if i have more errors.

**Comment by JHCD** [comment]
Hmm, works fine here...
Do you have installed other Mods?

**Comment by Riskke** [comment]
Just Wondrous Wonders but I don't see how can effect CQUI. I tried to reinstall the mod (still crashes) and last week I made a clean installation of Civ VI due a pc change... so really no clues about it

**Comment by papaguss** [comment]
I had the same problem,Issue was that the YnAMP (Play Europe Again Map). was the issue I re-created a game an chose another YnAMP map and I could use the slider agiain with no problem.
