### ISSUE TITLE
UI crashes when meeting new civ

### ISSUE THREAD

**Issue by smalltimepro** [chaorace/cqui#403]
The whole user interfaces completely vanishes when meeting a new civ. I have tested this in two separate games. Each time when I meet the first major civilization the UI vanishes. Even the hot keys dont work. Only keys that respond are 'Esc' and arrows to move the map. You can still roam the map and click on your units but nothing is actionable. The city banners and resource icons also get removed. Additionally the save and load game options become greyed out. I have a feeling this may be linked to leader animation play. 

p.s.
I have turned off leader animation from standard options.
I am using default CQUI options.
I am using some additional mods - AI Cleanup, AI+, Smoother Difficulty, TCS Omnibus Mod. None of these should theoretically have a conflict. I have attached a saved game file which crashes consistently/reliably after 1 turn.
[FREDERICK BARBAROSSA 119 75 AD.zip](https://github.com/chaorace/cqui/files/850293/FREDERICK.BARBAROSSA.119.75.AD.zip)

**Comment by smalltimepro** [comment]
I have made a subsequent test with all other mods disabled and same result. Game crash at first major civ meet.

**Comment by JHCD** [comment]
Two questions:
a) Civ Version?
b) CQUI Version?

**Comment by smalltimepro** [comment]
a) Civ Version: 1.0.0.56
b) CQUI version: nightly build

I have looking at a change made in Jan about fadescreen timing #214. could this be an unintended side effect?

**Comment by JHCD** [comment]
We use files and functions offer by the current Australian release (1.0.0.110) so you have to update your Civ Version for using CQUI.

**Comment by smalltimepro** [comment]
Okay. I made another test by removing the DiplomacyActionView.Lua and XML and that made a temp fix. I suppose the function calls you are referring to are housed in those files

**Comment by JHCD** [comment]
I do not think so...

**Comment by smalltimepro** [comment]
There was something related to diplomacyactionview anyway, since removing the related files made the leader screen run properly on my version. I suppose its a moot point though since I had the incorrect version as you pointed out. thanks.

**Comment by JHCD** [comment]
But I'm sure, that we have other new stuff, so it could be instable at other points too.

**Comment by chaorace** [comment]
@smalltimepro download the osx-linux version and tell me if that fixes the
issue

**Comment by novigit** [comment]
@JHCD I have observed the same issue as @smalltimepro . I'm using version 1.0.0.110 and the CQUI version of today.

**Comment by smalltimepro** [comment]
@novigit The issues went away from me when I upgraded to 110. I have used CQUI for several dozen hours since then and havent got any issues.

**Comment by novigit** [comment]
@JHCD @smalltimepro It turns out that my issue was not using the nightly build, but using the latest master branch copy. Now I use the nightly build with the spring patch of civ6, and the UI does not crash anymore upon meeting a civ :)
