### ISSUE TITLE
Buying a tile under district placing mode will exit city view

### ISSUE THREAD

**Issue by zxcvforz** [chaorace/cqui#46]
Steps:

1. Enter city view.
2. Select a district to place.
3. Buy a tile while in district placing mode.
4. The tile is purchased and the game automatically exits city view.

For reference, the save is attached, ready to buy a tile for the Holy Site.

[CQUI_Issue_46_BuyTileWhilePlacingExitsCity.zip](https://github.com/chaorace/cqui/files/573590/CQUI_Issue_46_BuyTileWhilePlacingExitsCity.zip)

**Comment by chaorace** [comment]
This is no longer the case as of 388cfc6b9b87cf345e470ac0fa5c57f87bb266b9

The behavior still isn't perfect: it exits district placing mode and goes back to regular cityview upon purchasing a tile, but it no longer kicks the player out of the cityview entirely
