### ISSUE TITLE
Nov 6 nightly build: the city screen wont let me change citizens, and it is showing the wrong City Details.

### ISSUE THREAD

**Issue by kemikalz** [chaorace/cqui#52]
Hey guys, got a bit of a problem tonight using the latest nightly build (Nov 6). Playing as Brazil, i took over 2 cities from Arabia. The problem is, when i go to the city view of the Arabian cities i own, they wont let me assign any citizens, and they are showing the City Details tab from whatever previous city i was in. It will only show the citizens in my own cities i made. If i open one of the Arabian cities, the City Details tab will show up as the last Brazilian city i looked at. Not sure whats wrong, i do use a few other mods, but they have nothing to do with the UI stuff. And this mod has been working flawlessly until i upgraded it tonight. I will attach some screenshots, save file, and a .rar of the mods i use. Thanks for your time to read this and all the hard work you guys do.

[http://imgur.com/3Oz9kgt](url)

[http://imgur.com/U4cZUih](url)

Dropbox link: https://www.dropbox.com/sh/i92mo6nyhfq89gk/AAA0bHi1clj8186wXvkTdZmDa?dl=0

I have never used dropbox for sharing files, hope it works. Let me know if there's any problems. Thanks.

**Comment by kemikalz** [comment]
UPDATE: i swapped out the CQUI version to an older one from yesterday (Nov 5), and opened up the Cairo city in my save game, and it is working fine. So i assume it must be an issue with the Nov 6 nightly build? Anyways, hope that helps a bit. Thanks everyone, take care

**Comment by chaorace** [comment]
@kemikalz Thanks for the report. This issue was caused by the religion icon trying to read nil data (the reason you were getting this bug was actually because the affected cities had majority religions!), which is a bug introduced from the process of combining the CQUI and Divine Yuri city panels. It should be fixed now and you can resume using the latest nightly if you like

**Comment by kemikalz** [comment]
Right on, glad that was easy for you to fix. Thanks so much, that was super quick.

**Comment by chaorace** [comment]
Haha, that's what happens when you have a noisy roommate who plays CS:GO at 3 AM. Say what you will about begrudged sleep deprivation, it helps get the bug-stomping juices flowing

**Comment by kemikalz** [comment]
Haha, that sucks... hope you can get some sleep man. Too bad Firaxis isn't paying you guys for all your hard work, you could get rid of that roommate :) Thanks again, loaded the save with your latest commit, and it is working great. Take care
