### ISSUE TITLE
Improving the Amenities panel of city view

### ISSUE THREAD

**Issue by zxcvforz** [chaorace/cqui#56]
1. Using the WrapWidth attribute

Firstly, <Label> tags can get the WrapWidth attribute to automatically warp long strings. When a word is longer than the WrapWidth, the word will be cut into two lines. This image shows WrapWidth="70" applied to the current amenities panel and removing the [NEWLINE] in the strings:

![289070_20161108154849_1c](https://cloud.githubusercontent.com/assets/6653593/20091288/ead4fc2a-a5cc-11e6-8820-5472649556db.jpg)

As can be seen, the "Entertainment" is split into two lines. Using the WrapWidth attribute allows the current hard-coded strings to use LOC_* strings that are localized. There doesn't seem to be a LOC_ string for "Entertainment", however, and more on this later.

There is a problem with using WrapWidth, though, and that is with people who modded their UI font sizes (me included). For us, the original list view is more flexible. The biggest problem with the City Details panel was the tutorial messages anyway.

2. Visually separate the "Total Amenities" line

Also referring to the previous image, I'd like to suggest that the "Total Amenities" line be done in the same way as the "Total Housing" line. Using the background color to separate it from the breakdown icons.

3. Internationalization

With the settings menu and perhaps even more elaborate configuration interface, it might be a good idea to get started on implementing i18n in the mod so that it can be localized.

This ties into item #1, where, with i18n implemented, all those labels should now get their own dedicated LOC strings to avoid future changes or conflicts, or localization differences making the panel look strange. When i18n is implemented, the "Entertainment" label can also get it's own LOC_ string.

**Comment by jacks0nX** [comment]
Good points, sounds reasonable.

**Comment by chaorace** [comment]
Addressing these in order:

1) See #4 for why we didn't go with WrapWidth, it was the original implementation and never really worked how we wanted.

2) This is a good idea and easy enough to implement with a line element

3) In regards to localization, I'm working on implementing it in the new settings menu that will be coming out soon.

**Comment by zyxpsilon** [comment]
Okay.. here's my take on this (related to the upcoming tries we'll have to make for **_Housing_** too!)

To me two very simple _combo-strings_ could solve all your problems of calibration.

1) Luxury -- Civic -- Entertainment -- Great People
... dropped straight above the four related Symbols/Values.
2) Religion -- National Parks -- War Wariness -- Bankruptcy
... these go below the related matchouts!

Now -- as you can see from this post the !TOTAL! length of the strings aren't balanced, visually.
Sooooo .. what exactly stops us from swapping "National Parks" with "Civic" & so on?? :)

People would then intuitively detect the proper string/text tag(s) as approximately stuck with the nearest symbol(s).

**Comment by zyxpsilon** [comment]
Ooooppppsss.. forgot to add another possibility; Tooltips for each "Bubbles'? :)

**Comment by zyxpsilon** [comment]
Something else i just noticed about this Panel.
When we start games in different Eras -- there's a (9th) slot for bonus Amenities. Not sure if you wanna break the neat block of 4x2 symbols for it though. But it still is part of normal total(s).
