### ISSUE TITLE
Cannot access/change city production

### ISSUE THREAD

**Issue by surak1701** [chaorace/cqui#57]
At some random point in the game, I'll no longer be able to access the city production window or any city related panel at all.  If I click to access the city, it does nothing but center the city on the map.  The only time city production is accessible is once the current project is finished.  This has happened in the last few games I've started.

At first I thought there might have been some conflict with another mod I was running, so I started a new game with only CQUI and the Aztecs modpacks activated.  Again, I've still lost the ability to access the city panels.  It's happened as early as around turn 20 and most recently at around turn 380 (I've attached that game's last save file).  I haven't changed any of the game files either.
[VICTORIA 381 300 AD.zip](https://github.com/chaorace/cqui/files/579058/VICTORIA.381.300.AD.zip)

**Comment by jacks0nX** [comment]
The save you attached still has both (CQUI and Yuri's) activated, most of the city related CQUI stuff seems to be overriden by yuri's mod. Can you attach a screenshot? Perhaps th mod order in the main menu even?

**Comment by surak1701** [comment]
You know what?  I'm an idiot.  Because Yuri's mod didn't show up in the additional content section, I just assumed it wasn't activated.  I did look at the mods associated with the save and somehow didn't see Yuri's.  I deleted Yuri's mod and just started a new game.  If there are any further issues, I'll post.  Thanks for checking so quickly!

**Comment by jacks0nX** [comment]
Neat, danger averted! :p
As far as I know @chaorace implemented yuri's mod in this one already, so you shouldn't need his (if you want).

**Comment by chaorace** [comment]
Yay! Not my fault! Closing issue now
