### ISSUE TITLE
Merged production screens

### ISSUE THREAD

**Issue by coreORB** [chaorace/cqui#59]
I've created in PS two mock-ups of merged production screens. They quite rough, but all elements are in place. Key improvements:
- removed tabs for: production, gold and faith
- added tabs for: all, building, units, wonders and projects (for less scrolling)
- added building queue (I've seen today @kblease queue, it's more polished so better use his)
- every position has buttons for every resource buy option
- if item is not purchase-able via resource, blank space is left (so that eq. gold is always in second column)

I think that this improvement will greatly reduce clicking :-).

![production1](https://cloud.githubusercontent.com/assets/6077897/20117605/9d99eeea-a601-11e6-9cc8-ec0b9cda65b3.png)
![production2](https://cloud.githubusercontent.com/assets/6077897/20117610/a03a9032-a601-11e6-8ec5-fc2c143b26ac.png)

**Comment by chaorace** [comment]
I definitely like the way #1 looks more but #2 is the more realistically easy to implement of the two, since the GridButton elements are already implemented. These are good concepts and I'll definitely see about expanding on them later, but I won't be starting on this until #34 is finished up because I don't want to interfere with that process.

**Comment by chaorace** [comment]
I'm making some considerable progress on this, expect something in the nightly soon!

**Comment by ProustIdee** [comment]
I hope this will be optional? I'd rather have tabs for purchasing with gold and faith (something I do infrequently) vs. tabs for switching between types of production (something I do constantly).

**Comment by chaorace** [comment]
It's the same as the production screen we have now, but with mini buttons
to gold/faith buy on them. No new tabs

**Comment by coreORB** [comment]
@chaorace Great to hear that! If You need some graphic assets (icons etc.) just let me know, I figure something out ;)

@ProustIdee Your edit is correct. First tab contains everything, next tabs: buildings, units, wonders and projects

**Comment by chaorace** [comment]
@coreORB Custom textures won't be possible until we get the SDK :\
