### ISSUE TITLE
Is it possible to show followers if there is no majority religion?

### ISSUE THREAD

**Issue by layzsmurf** [chaorace/cqui#68]
Currently the interface hides all followers unless there is a majority religion.

e.g. a city size 8 needs 4 followers for a majority religion - if that city has 2 followers of religion a and 3 of religion b, they do not show up in the religion lens. Thus it is quite hard to estimate when a city will flip or how effective missionaries are.

**Comment by chaorace** [comment]
@layzsmurf I believe this may already be possible by hovering over the religion tooltip in the citypanel after  Divine Yuri's Citypanel mod was integrated, but I haven't checked myself yet. If it isn't possible already, I know exactly what needs to be changed down to the line so this should be a very quick fix

**Comment by chaorace** [comment]
Yes this is already the case ![](http://i.imgur.com/CLFDrsg.png)

**Comment by layzsmurf** [comment]
I meant for an city. E.g. I want to flip an opposing city. If that city has adopted a religion I can see their followers in the religion lens (e.g. size 8 / 5 followers).

But if the majority is not reached, you cannot see the number of followers in a (foreign city) - e.g. size 8 and 3 followers - it might denote a few followers by showing a colored pantheon, but nothing more.

IMHO it would be nice that those followers are also shown in the religion lense.

**Comment by chaorace** [comment]
@layzsmurf I believe it may be possible, but I don't plan on implementing this because it's a strictly unfair advantage over non-users. Convenience is one thing, but this info is just not displayed at all anywhere

**Comment by layzsmurf** [comment]
Thank you chaorace the explanation - so far I have only played single player mode and did not think about the multiplayer implication.

So far cqui has been a great addition, thank you.
