### ISSUE TITLE
Add option: Choose new tech/civic button goes to tree instead of picker

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#72]

**Comment by vttale** [comment]
Strongly support this change.  Though it is easy to get to the trees via keybind, currently you've still got the extra panel unnecessarily open and needing to be closed.

**Comment by SpaceOgre** [comment]
Just a thought, atm when you reach the end of the Culture tree you can't reselect the last two (globalization and can't remember :p) you have to do it via the side panel. With this change it would be great to be able to do it from the tree.
