### ISSUE TITLE
Add option for CQUI settings to persist as defaults without saves

### ISSUE THREAD

**Issue by LordYanaek** [chaorace/cqui#76]
The new GUI is nice and the persistence of settings when you reload a game was definitely needed but it would be nice if users could also define the default state of those options so each time they start a new game, they get their preferred default behavior.
During my tests for keybindings, i found a way of doing this, with a few limitations.
- It is possible to create custom tables in the game database and read them from within the new config panel
- I can create an sql file, at the root of the mod folder to act like an ini for default settings. The "default state" for non-defined settings would thus be read from the database rather than hard coded when calling PopulateComboBox or PopulateCheckBox
- There would be no GUI for default state, users would have to define them by editing the sql file with a text editor but settings defined this way would be valid for every new game

If you're interested, i can try to create a commit with those changes (btw, i'm not sure using issues is the right way to handle such a discussion but apart from discussing it in the CivFanatics forum i'm not aware of another option)

**Comment by kblease** [comment]
@LordYanaek I think this is a perfectly fine place for a discussion like this one.

I think default settings would be great, especially as the number of settings will undoubtedly grow. I think the main barrier to doing that is exactly as you said, that there would be no GUI to modify the settings. That said, if someone feels comfortable editing the file then I think it makes sense for it to be there as an option. If someone would rather not, then they don't have to and it's no different than now.

**Comment by chaorace** [comment]
@LordYanaek I couldn't personally find a way to define non-save default settings that persist after restarting the client. If you have then I definitely invite you to so so!

**Comment by chaorace** [comment]
Resolved in #133
