### ISSUE TITLE
Government/Policies - Add Great People sort

### ISSUE THREAD

**Issue by layzsmurf** [chaorace/cqui#78]
Later in the game we have lots of policies. You can sort them by Millitary, Economic, Diplomatic or None.

This helps for most parts, except for purple policies, that are sorted to the back and you need to scroll for them in later eras.

One suggestion would be a new tab just for purple cards - or to reverse the sort order  - putting them purple cards at the start for none. This way it would be easier just to access those cards  - and if you need other policies you can access them with the existing categories.

**Comment by jacks0nX** [comment]
Good point, this was easy:

![image](https://cloud.githubusercontent.com/assets/2789832/20215569/62a77c88-a815-11e6-975c-4ce542867a16.png)

Going to send in a pull request.

**Comment by chaorace** [comment]
@jacks0nX Is this ready to submit as a PR?

**Comment by jacks0nX** [comment]
@chaorace yeah, when I manage to get my repo in order again.

**Comment by chaorace** [comment]
@jacks0nX I can just git cherry-pick 0948a03 if that's the only change

**Comment by jacks0nX** [comment]
Yes, these are the only changes.
