### ISSUE TITLE
Unable to purchase Units with gold!

### ISSUE THREAD

**Issue by Cobble23** [chaorace/cqui#79]
Hey there,

great work with the ui!
But I ran into a rather big issue as I am unable to buy units with gold.
It only shows the bulding tab for me and if I buy out all the buldings it says "No items are available..."
Screen: http://imgur.com/a/vDyIc

Additional mods I am running: "8 Ages of Pace" and "AI+" (dont see any conflict here?)
Tried deactivating them, same problem.

Apparently it works just fine for all the other people? :/

**Comment by brilang** [comment]
I ran into this same issue last night. I couldn't buy anything with gold, even though my top-bar gold amount showed enough. Two turns later, I could buy again. I think the top-bar gold amount was displaying an incorrect value.

**Comment by YellowFish085** [comment]
Same problem here.

I only have cqui installed.

I was playing with the [v0.6](https://github.com/chaorace/cqui/releases/tag/v0.6-alpha) but I had a bug with the production panel (sometimes it wouldn't show and I wasn't able to produce / buy anything), so I switched to the current version on the master branch. The production panel issue disappeared but now I can't buy any unit on the panel.

**Comment by kblease** [comment]
I got it taken care of and submitted a pull request. As soon as it is approved it should function as it used to.

**Comment by YellowFish085** [comment]
I tried the modification and it seems to be working fine.

Thanks for the quick fix !

**Comment by Cobble23** [comment]
Tried the fix and works just fine now. 
Thanks alot!

**Comment by dubert** [comment]
@Cobble23 You don't have enough Gold in the screenshot.
