### ISSUE TITLE
The camera starts centered on the absolute map center upon loading a save

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#83]
The expected behavior is that the camera starts centered on the capital. Unsure of how to fix this tbh, any ideas?

**Comment by RatchetJ** [comment]
We could register a function with this event: Events.LoadScreenClose() that centers the camera, similar to this function in CityPanel.lua:

-- ===========================================================================
--	Recenter camera on city
-- ===========================================================================
function RecenterCameraOnCity()
	local kCity:table = UI.GetHeadSelectedCity();
	UI.LookAtPlot( kCity:GetX(), kCity:GetY() );
end

**Comment by chaorace** [comment]
@RatchetJ Seems good, it can even go in CityPanel since the function already exist there

**Comment by RatchetJ** [comment]
I'll get started on this. It seems like this issue also exists on a fresh game as well. In that case should the camera start on the starting settler?

**Comment by chaorace** [comment]
Yes, good thinking on that one

**Comment by chaorace** [comment]
Fixed in PR #86
