### ISSUE TITLE
Add option to disable individual status messages

### ISSUE THREAD

**Issue by dubert** [chaorace/cqui#89]
I think one good option to have in the settings panels would be, "Which notifications do you want to receive every turn?"

Because right now, at the beginning of my turn, my screen is covered with:

"Research is completed"
"Civic is 50%"
"News from delegate"
"Tank was attacked"
"Tank attacked"
"Tank attacked"
"Tank took city"

And I'm like, "I know! I'm doing the attacking, I don't need a notification for it." I would personally disabled the military ones and science/civic 100% ones.

I'll attach a screenshot when I get back to my PC.

**Comment by chaorace** [comment]
Implemented in c8963130252a8cb90546423564eb6c22911e64ea

**Comment by chaorace** [comment]
Still working on exposing an option for the culture/tech status messages though
