### ISSUE TITLE
Production menu

### ISSUE THREAD

**Issue by BellyCrusher** [chaorace/cqui#90]
Everything works just fine but the production menu order isnt changed for me.
![untitled](https://cloud.githubusercontent.com/assets/23264573/20239689/861a9cc6-a906-11e6-898d-2fbcc5674bf8.jpg)

You know whats the case?

**Comment by ProustIdee** [comment]
Are you using the newest version?
https://github.com/chaorace/cqui/archive/master.zip

Is it turned on in the Add-Ons menu before you start the game?

Works fine for me.

**Comment by chaorace** [comment]
@BellyCrusher It's pretty clear from your screenshot that the mod isn't actually turned on. If it is, there's probably a mod conflict that's breaking CQUI, because multiple CQUI features seem to be inactive. I'm chalking this up to user error and closing the ticket for now. Feel free to keep posting in this thread for support though, I'd love to help sort this out!

**Comment by BellyCrusher** [comment]
As you can see other features are working for me. I'am only using YnAMP for civ 6. And nothing else.
Also I'am using newest version of the mod.  :/

![untitled](https://cloud.githubusercontent.com/assets/23264573/20249233/572c3092-a9f5-11e6-882e-fc62cce7b796.jpg)

**Comment by BellyCrusher** [comment]
I got this working. Somehow file got corrupted when downloading and this didint work. Download again and got this working.

**Comment by ProustIdee** [comment]
Hi BellyCrusher, your UI looks weird to me (the civilians look weird too, they shouldn't all be large).

Try deleting c:\Users\xxx\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui (and cqui-master if you're using the github master branch).

Unzip https://github.com/chaorace/cqui/archive/master.zip to C:\Users\xxx\Documents\My Games\Sid Meier's Civilization VI\Mods\cqui-master

Make sure you have "Chao Quick UI" turned on in your "Additional Content" menu (try running it without YnAMP to see if there is a conflict).

Start a new game (you can check to see if CQUI is running by hitting Escape and looking at the "MODS IN USE").
