### ISSUE TITLE
Improvement: Get boost amount from db instead of hardcoding value

### ISSUE THREAD

**Issue by SwingDancerMike** [chaorace/cqui#93]
Some mods adjust the inspiration/eureka percent amount using code like this

UPDATE Boosts SET Boost='25';

(China is always 10% greater.)

Request is to make the civic/tech complete warning pull the Boost variable, instead of hard-coding .5. Warning would go off at (1-(Boost/100)), and China would go off at (1-((Boost+10)/100)).

(This would happen in UI/CivicsTree.lua line 162 and UI/TechTree.lua line 153.)

**Comment by chaorace** [comment]
This is entirely reasonable, I'll see about getting this done
