### ISSUE TITLE
Gossip status messages are blank

### ISSUE THREAD

**Issue by ProustIdee** [chaorace/cqui#95]
Not sure if this is from CQUI, I'm planning to do a vanilla playthrough soon to check. My only other mod is AI+. I believe these may be delegate notifications, "Your delegate XXX noticed YYY..."?

![2016-11-13 10_26_50-sid meier s civilization vi dx11](https://cloud.githubusercontent.com/assets/15386719/20246744/d421eb74-a98b-11e6-8ce8-653fd99d2edd.png)

When I reload the autosave, I don't see it (I also don't get two notifications about irrigation):

![2016-11-13 10_28_59-sid meier s civilization vi dx11](https://cloud.githubusercontent.com/assets/15386719/20246771/4cd26760-a98c-11e6-9b1b-56fed5e5b129.png)

**Comment by SeanV12** [comment]
I also have this issue using only CQUI (current trunk)

**Comment by RatchetJ** [comment]
This might be a side effect of a bug with the 50% tech/civic notifications, which I think was just fixed. Try the most recent version and see if you're still getting the blank messages. If not I'll look into it.

**Comment by chaorace** [comment]
Yep, this is fixed in PR #91
