### ISSUE TITLE
Government legacy bonuses do not appear on some aspect ratios

### ISSUE THREAD

**Issue by ProustIdee** [chaorace/cqui#96]
In Civ 6 vanilla, the "My Government" tab shows you your legacy bonuses from maintaining your government over time (here +2% experience for combat units for Oligarchy):

![2016-11-13 13_33_52-sid meier s civilization vi dx11](https://cloud.githubusercontent.com/assets/15386719/20247876/edb552fa-a9a5-11e6-944f-183bf72fae4c.png)

As far as I know, there is no where in CQUI to find this information. If it's supposed to be in the "Change policies" tab (as seen [here ](https://camo.githubusercontent.com/e6228646709927b94488b605be8281e357c1597b/687474703a2f2f692e696d6775722e636f6d2f31363854684f782e6a7067)on the front page of the CQUI github project), it doesn't show up with my 16:10 1680x1050 monitor:

![2016-11-13 13_38_25-sid meier s civilization vi dx11](https://cloud.githubusercontent.com/assets/15386719/20247894/78bfacf6-a9a6-11e6-90db-0538777113cd.png)

**Comment by chaorace** [comment]
This is a strange one, do you have UI scaling enabled? I think the best solution to this problem is re-enabling the gov. tab in situations where the game disables that government side panel

**Comment by ProustIdee** [comment]
> This is a strange one, do you have UI scaling enabled? I think the best solution to this problem is re-enabling the gov. tab in situations where the game disables that government side panel.

You can't do UI scaling at 1680x1050
![2016-11-13 14_47_15-sid meier s civilization vi dx11](https://cloud.githubusercontent.com/assets/15386719/20248346/2ed89e4a-a9b0-11e6-9e9b-01fccca61a81.png)

**Comment by ProustIdee** [comment]
I don't know that much about the .xml UI files but just changing one line, it seems like there should be room, even on a 16:10 display:

Changing 675,700 here to 375,700:

`          <Container    ID="PolicyRows"                       Offset="0,0"    Size="375,700">`

![2016-11-13 19_34_46-sid meier s civilization vi dx11](https://cloud.githubusercontent.com/assets/15386719/20250158/61cd7d7a-a9d8-11e6-92e7-32a4fcdb0a73.png)

**Comment by chaorace** [comment]
@ProustIdee Yeah, that creates some room, but the tier 3 governments actually need that space for card slots

**Comment by ProustIdee** [comment]
@chaorace I realized that after I posted and I deleted my reply. I'm not that familiar with the UI code.

**Comment by Deminutiv** [comment]
Thanks for the mod and effort put into it, first of all. I like it a lot!

Anyway... i suffer from the same problem of hodden government (legacy) boni due to resolution. And looked through the mod-files but couldn't find anything to comment out to re-enable the "my government" tab - as you/chaorace suggested - and thus reached the ceiling of my modding capabilities, thus i'm posting here, asking for either pointers or a "guide" or something on how to renable the tab on my end. any help would be greatly appreciated.

**Comment by ProustIdee** [comment]
For now I just removed the GovernmentScreen.lua and GovernmentScreen.xml lines from the qui.modinfo file. It gives you the vanilla Government panels.

**Comment by Deminutiv** [comment]
i was searching for code exclusively the left-most tab and didn't think about the 'easy' solution, also fearing something else might hook into it and bug out. but your solution of removing the whole governmnent-screens-modificiations works perfectly as it seems, thanks a lot!

**Comment by JHCD** [comment]
Oh sorry, I have searched but nothing found...

My surface has 2736x1824 pixels on 12", so disable _UI Upscaling_ isn't a option.

**Comment by chaorace** [comment]
A temporary fix is available in the thread, it's not optimal but it's
there... You can also play on a non-native resolution that isn't scaled,
again, non-optimal, but available

**Comment by JHCD** [comment]
No, it's not possible to change the resolution...

![no-resolution](https://cloud.githubusercontent.com/assets/12496340/23169681/061bcd60-f84d-11e6-94c6-b18289a0f5c3.jpg)

I will take a look for the temporary fix...

**Comment by chaorace** [comment]
@JHCD Even from the ini settings? Also, [here's a link to the specific comment](https://github.com/chaorace/cqui/issues/96#issuecomment-263888622)

I hope it doesn't seem like I'm just writing your issue off, it's just not something I can easily reproduce myself and I can't seem to find anyone with the right resolution who's also willing to work on tackling this. I'm aware I can force the issue with ini settings myself, but my tiny native resolution can't hold the window at all, rendering QA for a fix like this very difficult

**Comment by JHCD** [comment]
Hi Chaorace,

no problem, I don't think so and I would support you to find it out.
I think the most simply solution is to bring back the _My Government_ tab, wenn _UI Upscaling_ is enabled. So you don't have to change your current tabs.

Regards,
Jens

**Comment by chaorace** [comment]
@JHCD [It seems we're on the same page then](https://github.com/chaorace/cqui/issues/96#issuecomment-260207070)

**Comment by JHCD** [comment]
@chaorace Is it possible to get the value of _UI Upsacale_?
So you could disable the changes in GovernmentScreen?

GovernmentScreen is the very same only without this _My Government_ tab - isn't it?
