### ISSUE TITLE
[Suggestion] Can you merge with Yuri's improved UI mod ?

### ISSUE THREAD

**Issue by Fangh** [chaorace/cqui#97]
Hello.

I love your work and I love [Yuri's work](https://forums.civfanatics.com/resources/divine-yuris-custom-city-panel.25430/).

Can the two mods be installed in the same time without bugs ?
Can you integrate his work inside yours ? (with conscent ofc)

Thank you !

**Comment by ProustIdee** [comment]
It already is, https://github.com/chaorace/cqui/commit/5a39f38035416356be4c90d60ef51fdfeadd9121

**Comment by Fangh** [comment]
wow ok sorry I didn't see that.
